using System.Globalization;

using ConduitLLM.Configuration;
using ConduitLLM.Configuration.Entities;
using ConduitLLM.Configuration.Interfaces;
using ConduitLLM.Persistence;
using ConduitLLM.Persistence.Interfaces;
using ConduitLLM.Persistence.Npgsql;

using Npgsql;

var configured = Environment.GetEnvironmentVariable("DATABASE_URL");
if (string.IsNullOrWhiteSpace(configured))
{
    Console.Error.WriteLine("DATABASE_URL is required.");
    return 2;
}

var connectionString = NormalizeConnectionString(configured);
var schema = $"conduit_aot_probe_{Guid.NewGuid():N}";

try
{
    await using var connection = new NpgsqlConnection(connectionString);
    await OpenWithRetryAsync(connection);
    await ExecuteAsync(connection, $"""
        CREATE SCHEMA "{schema}";
        CREATE TABLE "{schema}".records (
            id uuid PRIMARY KEY,
            version bigint NOT NULL,
            amount numeric(18,6) NOT NULL,
            payload jsonb NOT NULL,
            created_at timestamptz NOT NULL
        );
        CREATE TABLE "{schema}"."GlobalSettings" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Key" character varying(100) NOT NULL UNIQUE,
            "Value" character varying(2000) NOT NULL,
            "Description" character varying(500) NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL
        );
        CREATE TABLE "{schema}"."Providers" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ProviderType" integer NOT NULL,
            "ProviderName" character varying(100) NOT NULL,
            "BaseUrl" text NULL,
            "Settings" jsonb NULL,
            "IsEnabled" boolean NOT NULL,
            "TrustProviderReportedCosts" boolean NOT NULL,
            "ProviderCostMarkupMultiplier" numeric NOT NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL
        );
        CREATE TABLE "{schema}"."ProviderKeyCredentials" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ProviderId" integer NOT NULL REFERENCES "{schema}"."Providers" ("Id") ON DELETE CASCADE,
            "ProviderAccountGroup" smallint NOT NULL,
            "ApiKey" text NULL,
            "BaseUrl" text NULL,
            "SecretSettings" jsonb NULL,
            "KeyName" text NULL,
            "IsPrimary" boolean NOT NULL,
            "IsEnabled" boolean NOT NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL,
            CONSTRAINT "CK_PKC_AccountGroupRange"
                CHECK ("ProviderAccountGroup" >= 0 AND "ProviderAccountGroup" <= 32),
            CONSTRAINT "CK_PKC_PrimaryMustBeEnabled"
                CHECK ("IsPrimary" = false OR "IsEnabled" = true)
        );
        CREATE UNIQUE INDEX "IX_PKC_UniqueApiKey"
            ON "{schema}"."ProviderKeyCredentials" ("ProviderId", "ApiKey")
            WHERE "ApiKey" IS NOT NULL;
        CREATE UNIQUE INDEX "IX_PKC_OnePrimary"
            ON "{schema}"."ProviderKeyCredentials" ("ProviderId", "IsPrimary")
            WHERE "IsPrimary" = true;
        CREATE TABLE "{schema}"."ModelSeries" (
            "Id" integer PRIMARY KEY,
            "AuthorId" integer NOT NULL,
            "Name" text NOT NULL,
            "Description" text NULL,
            "TokenizerType" integer NOT NULL,
            "Parameters" text NOT NULL
        );
        CREATE TABLE "{schema}"."Models" (
            "Id" integer PRIMARY KEY,
            "Name" text NOT NULL,
            "Version" text NULL,
            "Description" text NULL,
            "ModelCardUrl" text NULL,
            "ModelSeriesId" integer NOT NULL REFERENCES "{schema}"."ModelSeries" ("Id"),
            "SupportsVision" boolean NOT NULL,
            "SupportsImageGeneration" boolean NOT NULL,
            "SupportsVideoGeneration" boolean NOT NULL,
            "SupportsEmbeddings" boolean NOT NULL,
            "SupportsSpeechToText" boolean NOT NULL,
            "SupportsTextToSpeech" boolean NOT NULL,
            "SupportsRerank" boolean NOT NULL,
            "SupportsChat" boolean NOT NULL,
            "SupportsFunctionCalling" boolean NOT NULL,
            "SupportsStreaming" boolean NOT NULL,
            "InputModalities" jsonb NULL,
            "OutputModalities" jsonb NULL,
            "CapabilitySource" integer NOT NULL,
            "CapabilitiesLastVerifiedAt" timestamptz NULL,
            "TokenizerType" integer NOT NULL,
            "MaxInputTokens" integer NULL,
            "MaxOutputTokens" integer NULL,
            "IsActive" boolean NOT NULL,
            "Parameters" text NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL
        );
        CREATE TABLE "{schema}"."ModelCosts" (
            "Id" integer PRIMARY KEY,
            "CostName" text NOT NULL,
            "PricingModel" integer NOT NULL,
            "PricingConfiguration" text NULL,
            "InputCostPerMillionTokens" numeric NOT NULL,
            "OutputCostPerMillionTokens" numeric NOT NULL,
            "EmbeddingCostPerMillionTokens" numeric NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL,
            "ModelType" text NOT NULL,
            "IsActive" boolean NOT NULL,
            "EffectiveDate" timestamptz NOT NULL,
            "ExpiryDate" timestamptz NULL,
            "Description" text NULL,
            "Priority" integer NOT NULL,
            "BatchProcessingMultiplier" numeric NULL,
            "SupportsBatchProcessing" boolean NOT NULL,
            "CachedInputCostPerMillionTokens" numeric NULL,
            "CachedInputWriteCostPerMillionTokens" numeric NULL,
            "CostPerSearchUnit" numeric NULL,
            "AudioCostPerMinute" numeric NULL,
            "AudioCostPerThousandCharacters" numeric NULL,
            "ReasoningCostPerMillionTokens" numeric NULL
        );
        CREATE TABLE "{schema}"."ModelIdentifiers" (
            "Id" integer PRIMARY KEY,
            "ModelId" integer NOT NULL REFERENCES "{schema}"."Models" ("Id"),
            "IsEnabled" boolean NOT NULL,
            "MaxInputTokens" integer NULL,
            "MaxOutputTokens" integer NULL,
            "InputModalities" jsonb NULL,
            "OutputModalities" jsonb NULL,
            "OperationalCapabilities" jsonb NULL,
            "CapabilitySource" integer NULL,
            "CapabilitiesLastVerifiedAt" timestamptz NULL,
            "ProviderVariation" text NULL,
            "QualityScore" numeric NULL,
            "SpeedScore" numeric NULL,
            "Identifier" text NOT NULL,
            "Provider" integer NULL,
            "ModelCostId" integer NULL REFERENCES "{schema}"."ModelCosts" ("Id"),
            "IsPrimary" boolean NOT NULL,
            "Metadata" text NULL
        );
        CREATE TABLE "{schema}"."ModelProviderMappings" (
            "Id" integer PRIMARY KEY,
            "ModelAlias" text NOT NULL,
            "ProviderModelId" text NOT NULL,
            "ProviderId" integer NOT NULL REFERENCES "{schema}"."Providers" ("Id"),
            "IsEnabled" boolean NOT NULL,
            "RoutingPriority" integer NOT NULL,
            "RoutingWeight" numeric NOT NULL,
            "ProviderOptions" text NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL,
            "ModelProviderTypeAssociationId" integer NOT NULL REFERENCES "{schema}"."ModelIdentifiers" ("Id")
        );
        CREATE TABLE "{schema}"."ModelRoutePolicies" (
            "Id" integer PRIMARY KEY,
            "ModelAlias" text NOT NULL,
            "Strategy" text NOT NULL,
            "CostWeight" numeric NOT NULL,
            "SpeedWeight" numeric NOT NULL,
            "QualityWeight" numeric NOT NULL,
            "CacheAffinityEnabled" boolean NOT NULL,
            "AffinityTtlSeconds" integer NOT NULL,
            "MaxAffinityScorePenalty" numeric NOT NULL,
            "IsEnabled" boolean NOT NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL
        );
        CREATE TABLE "{schema}"."VirtualKeyGroups" (
            "Id" integer PRIMARY KEY,
            "ExternalGroupId" character varying(100) NULL,
            "GroupName" character varying(100) NOT NULL,
            "Balance" numeric(19,8) NOT NULL,
            "LifetimeCreditsAdded" numeric(19,8) NOT NULL,
            "LifetimeSpent" numeric(19,8) NOT NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL,
            "MediaRetentionPolicyId" integer NULL,
            "RateLimitRpm" integer NULL,
            "RateLimitRpd" integer NULL,
            "RateLimitTpm" integer NULL,
            "MaxParallelRequests" integer NULL,
            "RowVersion" bytea NULL
        );
        INSERT INTO "{schema}"."VirtualKeyGroups" (
            "Id", "GroupName", "Balance", "LifetimeCreditsAdded", "LifetimeSpent",
            "CreatedAt", "UpdatedAt", "RateLimitRpm", "MaxParallelRequests")
        VALUES (7, 'native runtime group', 25, 25, 0, now(), now(), 500, 10);
        CREATE TABLE "{schema}"."VirtualKeys" (
            "Id" integer PRIMARY KEY,
            "KeyName" character varying(100) NOT NULL,
            "KeyHash" character varying(128) NOT NULL UNIQUE,
            "Description" character varying(500) NULL,
            "IsEnabled" boolean NOT NULL,
            "VirtualKeyGroupId" integer NOT NULL REFERENCES "{schema}"."VirtualKeyGroups" ("Id") ON DELETE RESTRICT,
            "ExpiresAt" timestamptz NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL,
            "Metadata" text NULL,
            "AllowedModels" text NULL,
            "RateLimitRpm" integer NULL,
            "RateLimitRpd" integer NULL,
            "RateLimitTpm" integer NULL,
            "MaxParallelRequests" integer NULL,
            "RateLimitPriority" integer NULL,
            "ModelRateLimits" jsonb NULL,
            "RowVersion" bytea NULL
        );
        INSERT INTO "{schema}"."VirtualKeys" (
            "Id", "KeyName", "KeyHash", "IsEnabled", "VirtualKeyGroupId",
            "CreatedAt", "UpdatedAt", "AllowedModels", "RateLimitRpm",
            "ModelRateLimits")
        VALUES
            (41, 'native key 41', 'native-hash-41', true, 7, now(), now(), 'gpt-5', 100, jsonb_build_object('gpt-5', jsonb_build_object('rpm', 5))),
            (42, 'native key 42', 'native-hash-42', true, 7, now(), now(), NULL, NULL, NULL);
        CREATE TABLE "{schema}"."MediaRetentionPolicies" (
            "Id" integer PRIMARY KEY,
            "Name" character varying(100) NOT NULL,
            "Description" character varying(500) NULL,
            "PositiveBalanceRetentionDays" integer NOT NULL,
            "ZeroBalanceRetentionDays" integer NOT NULL,
            "NegativeBalanceRetentionDays" integer NOT NULL,
            "SoftDeleteGracePeriodDays" integer NOT NULL,
            "RespectRecentAccess" boolean NOT NULL,
            "RecentAccessWindowDays" integer NOT NULL,
            "IsDefault" boolean NOT NULL,
            "MaxStorageSizeBytes" bigint NULL,
            "MaxFileCount" integer NULL,
            "QuotaExceededBehavior" integer NOT NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL,
            "IsActive" boolean NOT NULL
        );
        INSERT INTO "{schema}"."MediaRetentionPolicies" (
            "Id", "Name", "PositiveBalanceRetentionDays", "ZeroBalanceRetentionDays",
            "NegativeBalanceRetentionDays", "SoftDeleteGracePeriodDays",
            "RespectRecentAccess", "RecentAccessWindowDays", "IsDefault",
            "MaxStorageSizeBytes", "MaxFileCount", "QuotaExceededBehavior",
            "CreatedAt", "UpdatedAt", "IsActive")
        VALUES (1, 'native default', 60, 14, 3, 7, true, 7, true,
            1000, 5, 0, now(), now(), true);
        CREATE TABLE "{schema}"."MediaRecords" (
            "Id" uuid PRIMARY KEY,
            "StorageKey" character varying(500) NOT NULL UNIQUE,
            "VirtualKeyId" integer NOT NULL REFERENCES "{schema}"."VirtualKeys" ("Id") ON DELETE CASCADE,
            "MediaType" character varying(50) NOT NULL,
            "ContentType" character varying(100) NULL,
            "SizeBytes" bigint NULL,
            "ContentHash" character varying(64) NULL,
            "Provider" character varying(50) NULL,
            "Model" character varying(100) NULL,
            "Prompt" text NULL,
            "StorageUrl" text NULL,
            "PublicUrl" text NULL,
            "ExpiresAt" timestamptz NULL,
            "CreatedAt" timestamptz NOT NULL,
            "LastAccessedAt" timestamptz NULL,
            "AccessCount" integer NOT NULL,
            "DeletedAt" timestamptz NULL
        );
        CREATE TABLE "{schema}"."VirtualKeyGroupTransactions" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "VirtualKeyGroupId" integer NOT NULL REFERENCES "{schema}"."VirtualKeyGroups" ("Id") ON DELETE CASCADE,
            "TransactionType" integer NOT NULL,
            "Amount" numeric(18,6) NOT NULL,
            "BalanceAfter" numeric(18,6) NOT NULL,
            "ReferenceType" integer NOT NULL,
            "ReferenceId" character varying(100) NULL,
            "Description" character varying(500) NULL,
            "InitiatedBy" character varying(50) NOT NULL,
            "InitiatedByUserId" character varying(100) NULL,
            "IdempotencyKey" character varying(100) NULL,
            "BillingWindowStartUtc" timestamptz NULL,
            "CreatedAt" timestamptz NOT NULL,
            "IsDeleted" boolean NOT NULL,
            "DeletedAt" timestamptz NULL
        );
        CREATE UNIQUE INDEX "IX_VKGT_IdempotencyKey"
            ON "{schema}"."VirtualKeyGroupTransactions" ("IdempotencyKey")
            WHERE "IdempotencyKey" IS NOT NULL;
        CREATE TABLE "{schema}"."RequestLogs" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "VirtualKeyId" integer NOT NULL REFERENCES "{schema}"."VirtualKeys" ("Id") ON DELETE CASCADE,
            "ModelName" character varying(100) NOT NULL,
            "ProviderId" integer NULL,
            "ProviderType" character varying(50) NULL,
            "ModelProviderMappingId" integer NULL,
            "PromptCachingEligible" boolean NOT NULL,
            "PromptCachingPolicyApplied" boolean NOT NULL,
            "CachedReadSavings" numeric(18,8) NOT NULL,
            "CacheWritePremium" numeric(18,8) NOT NULL,
            "RoutingAffinityUsed" boolean NOT NULL,
            "RoutingDecisionReason" character varying(50) NULL,
            "RoutingFailoverCount" integer NOT NULL,
            "RequestType" character varying(50) NOT NULL,
            "InputTokens" integer NOT NULL,
            "OutputTokens" integer NOT NULL,
            "CachedInputTokens" integer NULL,
            "CachedWriteTokens" integer NULL,
            "Cost" numeric(10,6) NOT NULL,
            "BillingMethod" integer NULL,
            "ProviderReportedCostUsd" numeric(18,8) NULL,
            "ProviderCostMarkupMultiplier" numeric(18,8) NULL,
            "BilledAtUtc" timestamptz NULL,
            "ResponseTimeMs" double precision NOT NULL,
            "Timestamp" timestamptz NOT NULL,
            "UserId" character varying(100) NULL,
            "ClientIp" character varying(50) NULL,
            "RequestPath" character varying(256) NULL,
            "StatusCode" integer NULL,
            "Metadata" jsonb NULL
        );
        CREATE TABLE "{schema}"."IpFilters" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "FilterType" character varying(10) NOT NULL,
            "IpAddressOrCidr" character varying(50) NOT NULL,
            "Name" character varying(100) NULL,
            "Description" character varying(500) NULL,
            "IsEnabled" boolean NOT NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL,
            "CreatedBy" character varying(100) NULL,
            "UpdatedBy" character varying(100) NULL,
            "VirtualKeyId" integer NULL REFERENCES "{schema}"."VirtualKeys" ("Id") ON DELETE CASCADE,
            "RowVersion" bytea NULL
        );
        CREATE TABLE "{schema}"."AsyncTasks" (
            "Id" character varying(50) PRIMARY KEY,
            "Type" character varying(100) NOT NULL,
            "State" integer NOT NULL,
            "Payload" text NULL,
            "Progress" integer NOT NULL,
            "ProgressMessage" character varying(500) NULL,
            "Result" text NULL,
            "Error" text NULL,
            "CreatedAt" timestamptz NOT NULL,
            "UpdatedAt" timestamptz NOT NULL,
            "CompletedAt" timestamptz NULL,
            "VirtualKeyId" integer NOT NULL,
            "Metadata" text NULL,
            "IsArchived" boolean NOT NULL,
            "ArchivedAt" timestamptz NULL,
            "LeasedBy" character varying(100) NULL,
            "LeaseExpiryTime" timestamptz NULL,
            "ProviderInvocationStartedAt" timestamptz NULL,
            "ProviderInvocationCompletedAt" timestamptz NULL,
            "ProviderOperationId" character varying(200) NULL,
            "RetryDispatchId" character varying(64) NULL,
            "Version" integer NOT NULL,
            "RetryCount" integer NOT NULL,
            "MaxRetries" integer NOT NULL,
            "IsRetryable" boolean NOT NULL,
            "NextRetryAt" timestamptz NULL
        );
        """);

    var id = Guid.NewGuid();
    var createdAt = DateTimeOffset.UtcNow;
    await using (var insert = new NpgsqlCommand(
        $"INSERT INTO \"{schema}\".records VALUES (@id, 0, @amount, @payload::jsonb, @created)", connection))
    {
        insert.Parameters.AddWithValue("id", id);
        insert.Parameters.AddWithValue("amount", 12.345678m);
        insert.Parameters.AddWithValue("payload", "{\"kind\":\"native\"}");
        insert.Parameters.AddWithValue("created", createdAt);
        Ensure(await insert.ExecuteNonQueryAsync() == 1, "write failed");
    }

    await using (var read = new NpgsqlCommand(
        $"SELECT amount, payload->>'kind', created_at FROM \"{schema}\".records WHERE id=@id", connection))
    {
        read.Parameters.AddWithValue("id", id);
        await using var reader = await read.ExecuteReaderAsync();
        Ensure(await reader.ReadAsync(), "read failed");
        Ensure(reader.GetDecimal(0) == 12.345678m, "numeric mapping failed");
        Ensure(reader.GetString(1) == "native", "jsonb mapping failed");
        Ensure(reader.GetFieldValue<DateTime>(2).Kind == DateTimeKind.Utc, "timestamptz mapping failed");
    }

    await using (var transaction = await connection.BeginTransactionAsync())
    {
        await using var rolledBack = new NpgsqlCommand(
            $"INSERT INTO \"{schema}\".records VALUES (@id, 0, 1, '{{}}', now())", connection, transaction);
        rolledBack.Parameters.AddWithValue("id", Guid.NewGuid());
        await rolledBack.ExecuteNonQueryAsync();
        await transaction.RollbackAsync();
    }
    Ensure(await ScalarAsync<long>(connection, $"SELECT count(*) FROM \"{schema}\".records") == 1, "rollback failed");

    var updates = await Task.WhenAll(
        TryOptimisticUpdateAsync(connectionString, schema, id),
        TryOptimisticUpdateAsync(connectionString, schema, id));
    Ensure(updates.Sum() == 1, "optimistic concurrency failed");

    var attempts = 0;
    await RetrySerializationAsync(async () =>
    {
        attempts++;
        if (attempts == 1)
        {
            await ExecuteAsync(connection, "SET SESSION application_name = 'conduit-aot-retry-ready'");
            await ExecuteAsync(connection, "DO $$ BEGIN RAISE EXCEPTION 'retry probe' USING ERRCODE='40001'; END $$;");
        }
        return await ScalarAsync<int>(connection, "SELECT 1");
    });
    Ensure(attempts == 2, "serialization retry failed");

    var storeConnectionString = new NpgsqlConnectionStringBuilder(connectionString)
    {
        SearchPath = schema
    }.ConnectionString;
    await using (var dataSource = NpgsqlDataSource.Create(storeConnectionString))
    {
        await ExerciseGlobalSettingRepositoryAsync(new NpgsqlGlobalSettingRepository(dataSource));
        await ExerciseIpFilterRepositoryAsync(new NpgsqlIpFilterRepository(dataSource));
        await ExerciseProviderPersistenceAsync(
            new NpgsqlProviderRepository(dataSource),
            new NpgsqlProviderKeyCredentialRepository(dataSource));
        await ExerciseModelRoutingRuntimeStoreAsync(
            dataSource,
            new NpgsqlModelProviderMappingRuntimeStore(dataSource));
        await ExerciseVirtualKeyRuntimeStoreAsync(new NpgsqlVirtualKeyRuntimeStore(dataSource));
        await ExerciseMediaRuntimeStoreAsync(new NpgsqlMediaRuntimeStore(dataSource));
        await ExerciseAsyncTaskRuntimeStoreAsync(new NpgsqlAsyncTaskRuntimeStore(dataSource));
        await ExerciseRequestLogRuntimeStoreAsync(
            dataSource,
            new NpgsqlRequestLogRuntimeStore(dataSource));
    }

    Console.WriteLine("Native persistence probe passed: reads, writes, rollback, concurrency, retry, PostgreSQL mappings, and the global-settings, IP-filter, provider/credential, model-routing, virtual-key, media, async-task, and request-log runtime stores.");
    return 0;
}
finally
{
    try
    {
        await using var cleanup = new NpgsqlConnection(connectionString);
        await cleanup.OpenAsync();
        await ExecuteAsync(cleanup, $"DROP SCHEMA IF EXISTS \"{schema}\" CASCADE");
    }
    catch (Exception exception)
    {
        Console.Error.WriteLine($"Cleanup failed: {exception.Message}");
    }
}

static string NormalizeConnectionString(string configured)
{
    if (!Uri.TryCreate(configured, UriKind.Absolute, out var uri) ||
        (uri.Scheme != "postgres" && uri.Scheme != "postgresql"))
    {
        return configured;
    }

    var credentials = uri.UserInfo.Split(':', 2);
    return new NpgsqlConnectionStringBuilder
    {
        Host = uri.Host,
        Port = uri.IsDefaultPort ? 5432 : uri.Port,
        Database = uri.AbsolutePath.TrimStart('/'),
        Username = Uri.UnescapeDataString(credentials[0]),
        Password = credentials.Length == 2 ? Uri.UnescapeDataString(credentials[1]) : string.Empty
    }.ConnectionString;
}

static async Task OpenWithRetryAsync(NpgsqlConnection connection)
{
    for (var attempt = 1; ; attempt++)
    {
        try
        {
            await connection.OpenAsync();
            return;
        }
        catch (NpgsqlException) when (attempt < 4)
        {
            await Task.Delay(TimeSpan.FromMilliseconds(100 * attempt));
        }
    }
}

static async Task<int> TryOptimisticUpdateAsync(string connectionString, string schema, Guid id)
{
    await using var connection = new NpgsqlConnection(connectionString);
    await connection.OpenAsync();
    await using var command = new NpgsqlCommand(
        $"UPDATE \"{schema}\".records SET version=version+1 WHERE id=@id AND version=0", connection);
    command.Parameters.AddWithValue("id", id);
    return await command.ExecuteNonQueryAsync();
}

static async Task<T> RetrySerializationAsync<T>(Func<Task<T>> operation)
{
    for (var attempt = 1; ; attempt++)
    {
        try
        {
            return await operation();
        }
        catch (PostgresException exception) when (exception.SqlState == "40001" && attempt < 3)
        {
            await Task.Delay(TimeSpan.FromMilliseconds(25 * attempt));
        }
    }
}

static async Task ExecuteAsync(NpgsqlConnection connection, string sql)
{
    await using var command = new NpgsqlCommand(sql, connection);
    await command.ExecuteNonQueryAsync();
}

static async Task<T> ScalarAsync<T>(NpgsqlConnection connection, string sql)
{
    await using var command = new NpgsqlCommand(sql, connection);
    var value = await command.ExecuteScalarAsync();
    return (T)Convert.ChangeType(value!, typeof(T), CultureInfo.InvariantCulture);
}

static async Task ExerciseGlobalSettingRepositoryAsync(IGlobalSettingRepository repository)
{
    Ensure((await repository.ListAsync()).Count == 0, "global-settings initial list failed");

    var setting = new GlobalSetting
    {
        Key = "native.probe",
        Value = "one",
        Description = "initial",
        CreatedAt = default
    };
    var id = await repository.CreateAsync(setting);
    Ensure(id > 0 && setting.Id == id, "global-settings create failed");

    var byId = await repository.GetByIdAsync(id)
        ?? throw new InvalidOperationException("global-settings ID lookup failed");
    Ensure(byId.Key == setting.Key, "global-settings ID lookup failed");
    Ensure(byId.CreatedAt.Kind == DateTimeKind.Utc, "global-settings UTC mapping failed");

    byId.Value = "two";
    byId.Description = null;
    Ensure(await repository.UpdateAsync(byId), "global-settings update failed");
    Ensure((await repository.GetByKeyAsync(setting.Key))?.Description is null,
        "global-settings nullable mapping failed");

    Ensure(await repository.UpsertAsync(setting.Key, "three", "restored"),
        "global-settings update upsert failed");
    Ensure(await repository.UpsertAsync(setting.Key, "four"),
        "global-settings description-preserving upsert failed");
    var afterUpsert = await repository.GetByKeyAsync(setting.Key);
    Ensure(afterUpsert is { Value: "four", Description: "restored" },
        "global-settings upsert semantics failed");

    Ensure(await repository.UpsertAsync("native.alpha", "first"),
        "global-settings insert upsert failed");
    var settings = await repository.ListAsync();
    Ensure(settings.Count == 2 && settings[0].Key == "native.alpha" && settings[1].Key == setting.Key,
        "global-settings ordered list failed");

    Ensure(await repository.DeleteAsync(id), "global-settings ID delete failed");
    Ensure(await repository.DeleteByKeyAsync("native.alpha"), "global-settings key delete failed");
    Ensure((await repository.ListAsync()).Count == 0, "global-settings cleanup failed");
}

static async Task ExerciseIpFilterRepositoryAsync(IIpFilterRepository repository)
{
    Ensure((await repository.ListAsync()).Count == 0, "IP-filter initial list failed");

    var global = await repository.AddAsync(new IpFilterEntity
    {
        FilterType = "blacklist",
        IpAddressOrCidr = "10.0.0.0/8",
        Name = "native global",
        IsEnabled = true,
        CreatedAt = default
    });
    var keyRule = await repository.AddAsync(new IpFilterEntity
    {
        FilterType = "whitelist",
        IpAddressOrCidr = "192.0.2.0/24",
        Description = "native per-key",
        IsEnabled = true,
        VirtualKeyId = 41
    });
    await repository.AddAsync(new IpFilterEntity
    {
        FilterType = "blacklist",
        IpAddressOrCidr = "198.51.100.0/24",
        IsEnabled = false,
        VirtualKeyId = 42
    });

    Ensure(global.Id > 0 && keyRule.Id > 0, "IP-filter create failed");
    Ensure(global.CreatedAt.Kind == DateTimeKind.Utc, "IP-filter UTC mapping failed");
    Ensure((await repository.GetEnabledAsync()).Count == 1, "IP-filter global scope failed");
    Ensure((await repository.GetEnabledPerKeyAsync()).Count == 1, "IP-filter per-key scope failed");
    Ensure((await repository.GetByVirtualKeyIdAsync(42)).Count == 1, "IP-filter key lookup failed");

    var byId = await repository.GetByIdAsync(global.Id)
        ?? throw new InvalidOperationException("IP-filter ID lookup failed");
    byId.Name = "updated native global";
    byId.Description = null;
    Ensure(await repository.UpdateAsync(byId), "IP-filter update failed");
    Ensure((await repository.GetByIdAsync(global.Id))?.Name == "updated native global",
        "IP-filter updated value lookup failed");

    foreach (var filter in await repository.ListAsync())
    {
        Ensure(await repository.DeleteAsync(filter.Id), "IP-filter delete failed");
    }

    Ensure((await repository.ListAsync()).Count == 0, "IP-filter cleanup failed");
}

static async Task ExerciseProviderPersistenceAsync(
    IProviderRepository providers,
    IProviderKeyCredentialRepository credentials)
{
    var provider = new Provider
    {
        ProviderType = ProviderType.OpenAI,
        ProviderName = "native provider",
        Settings = new Dictionary<string, string> { ["region"] = "west" },
        IsEnabled = true,
        TrustProviderReportedCosts = true,
        ProviderCostMarkupMultiplier = 1.125m,
        CreatedAt = default
    };
    Ensure(await providers.CreateAsync(provider) > 0, "provider create failed");

    var first = new ProviderKeyCredential
    {
        ProviderId = provider.Id,
        ApiKey = "enc:v1:native-first",
        SecretSettings = new Dictionary<string, string> { ["secret"] = "enc:v1:value" },
        KeyName = "first",
        IsEnabled = true
    };
    var second = new ProviderKeyCredential
    {
        ProviderId = provider.Id,
        ProviderAccountGroup = 1,
        ApiKey = "enc:v1:native-second",
        KeyName = "second",
        IsEnabled = true
    };
    Ensure(await credentials.CreateAsync(first) > 0 && first.IsPrimary,
        "credential automatic primary failed");
    Ensure(await credentials.CreateAsync(second) > 0 && !second.IsPrimary,
        "credential secondary create failed");
    Ensure(await credentials.SetPrimaryKeyAsync(provider.Id, second.Id),
        "credential primary rotation failed");

    var loaded = await credentials.GetByIdAsync(second.Id)
        ?? throw new InvalidOperationException("credential lookup failed");
    loaded.ApiKey = "enc:v1:native-rotated";
    loaded.SecretSettings = new Dictionary<string, string> { ["secret"] = "enc:v1:rotated" };
    loaded.KeyName = "rotated";
    Ensure(await credentials.UpdateAsync(loaded), "credential update failed");
    Ensure((await credentials.GetPrimaryKeyAsync(provider.Id))?.Id == second.Id,
        "credential primary lookup failed");
    Ensure((await credentials.GetByIdAsync(second.Id))?.SecretSettings?["secret"] == "enc:v1:rotated",
        "credential JSONB mapping failed");

    var hydrated = await providers.GetByIdAsync(provider.Id)
        ?? throw new InvalidOperationException("provider lookup failed");
    Ensure(hydrated.ProviderKeyCredentials.Count == 2, "provider credential hydration failed");
    Ensure(hydrated.Settings?["region"] == "west", "provider JSONB mapping failed");

    Ensure(await providers.DeleteAsync(provider.Id), "provider cascade delete failed");
    Ensure(await credentials.CountByProviderIdAsync(provider.Id) == 0,
        "provider credential cascade failed");
}

static async Task ExerciseVirtualKeyRuntimeStoreAsync(IVirtualKeyRuntimeStore store)
{
    var key = await store.GetByHashAsync("native-hash-41")
        ?? throw new InvalidOperationException("virtual-key runtime hash lookup failed");
    Ensure(key.Id == 41 && key.Group.Id == 7, "virtual-key runtime hydration failed");
    Ensure(key.Group.Balance == 25m, "virtual-key runtime group mapping failed");
    Ensure(key.ModelRateLimits?.Contains("gpt-5", StringComparison.Ordinal) == true,
        "virtual-key runtime JSONB mapping failed");
    Ensure((await store.GetKeyHashesByGroupIdAsync(7)).SequenceEqual(
            ["native-hash-41", "native-hash-42"]),
        "virtual-key runtime group hash lookup failed");

    var touchedAt = DateTime.UtcNow.AddMinutes(1);
    Ensure(await store.TouchAsync(key.Id, touchedAt), "virtual-key runtime touch failed");
    var touched = (await store.GetByIdAsync(key.Id))?.UpdatedAt
        ?? throw new InvalidOperationException("virtual-key runtime touched key lookup failed");
    Ensure((touched - touchedAt).Duration() < TimeSpan.FromMilliseconds(1),
        "virtual-key runtime touched timestamp failed");

    var debit = await store.AdjustBalanceAsync(new VirtualKeyBalanceAdjustment(
        key.Group.Id,
        -1m,
        "native charge",
        "NativeProbe",
        VirtualKeyBalanceReferenceType.VirtualKey,
        key.Id.ToString(CultureInfo.InvariantCulture)));
    Ensure(debit.Applied && debit.NewBalance == 24m && debit.LifetimeSpent == 1m,
        "virtual-key runtime debit failed");

    var delivery = new VirtualKeyBalanceAdjustment(
        key.Group.Id,
        -2m,
        "native idempotent charge",
        "NativeProbe",
        VirtualKeyBalanceReferenceType.VirtualKey,
        key.Id.ToString(CultureInfo.InvariantCulture),
        "native:delivery-1");
    Ensure((await store.AdjustBalanceAsync(delivery)).Applied,
        "virtual-key runtime idempotent first delivery failed");
    Ensure(!(await store.AdjustBalanceAsync(delivery)).Applied,
        "virtual-key runtime idempotent replay failed");

    var concurrent = await Task.WhenAll(Enumerable.Range(0, 4).Select(index =>
        store.AdjustBalanceAsync(new VirtualKeyBalanceAdjustment(
            key.Group.Id,
            -0.25m,
            $"native concurrent {index}",
            "NativeProbe",
            VirtualKeyBalanceReferenceType.VirtualKey,
            key.Id.ToString(CultureInfo.InvariantCulture)))));
    Ensure(concurrent.Select(result => result.NewBalance).Distinct().Count() == 4,
        "virtual-key runtime concurrent updates were lost");

    var credit = await store.AdjustBalanceAsync(new VirtualKeyBalanceAdjustment(
        key.Group.Id,
        4m,
        null,
        null,
        VirtualKeyBalanceReferenceType.Manual));
    Ensure(credit.NewBalance == 25m && credit.LifetimeSpent == 4m,
        "virtual-key runtime credit or lifetime counters failed");
}

static async Task ExerciseMediaRuntimeStoreAsync(IMediaRuntimeStore store)
{
    var active = new MediaRuntimeRecord
    {
        Id = Guid.NewGuid(),
        StorageKey = "native/media.png",
        VirtualKeyId = 41,
        MediaType = "image",
        ContentType = "image/png",
        SizeBytes = 64,
        ContentHash = new string('a', 64),
        Provider = "native-provider",
        Model = "native-image-model",
        Prompt = "native media persistence",
        StorageUrl = "s3://native/media.png",
        CreatedAt = DateTime.UtcNow
    };
    Ensure(await store.CreateAsync(active) == active.Id, "media runtime create failed");
    var replay = new MediaRuntimeRecord
    {
        StorageKey = active.StorageKey,
        VirtualKeyId = active.VirtualKeyId,
        MediaType = active.MediaType,
        SizeBytes = 999,
        Provider = "replayed-provider"
    };
    Ensure(await store.CreateAsync(replay) == active.Id && replay.Id == active.Id,
        "media runtime idempotent storage-key replay failed");
    Ensure((await store.GetByStorageKeyAsync(active.StorageKey))?.VirtualKeyId == 41,
        "media runtime storage-key lookup failed");

    var deleted = new MediaRuntimeRecord
    {
        Id = Guid.NewGuid(),
        StorageKey = "native/deleted.png",
        VirtualKeyId = 41,
        MediaType = "image",
        SizeBytes = 16,
        CreatedAt = DateTime.UtcNow,
        DeletedAt = DateTime.UtcNow
    };
    await store.CreateAsync(deleted);
    Ensure(await store.GetByStorageKeyAsync(deleted.StorageKey) is null,
        "media runtime soft-delete filter failed");
    Ensure((await store.GetByStorageKeyAsync(deleted.StorageKey, includeDeleted: true))?.DeletedAt is not null,
        "media runtime tombstone lookup failed");

    Ensure(await store.UpdateAccessStatsAsync(active.Id), "media runtime access update failed");
    Ensure((await store.GetByStorageKeyAsync(active.StorageKey))?.AccessCount == 1,
        "media runtime access counter failed");
    Ensure((await store.GetByVirtualKeyIdAsync(41)).Count == 1,
        "media runtime ownership listing failed");

    var aggregate = await store.GetAggregateStorageStatsAsync(7);
    Ensure(aggregate.TotalFiles == 1 && aggregate.TotalSizeBytes == 64,
        "media runtime active aggregate failed");
    Ensure(aggregate.ByProvider.TryGetValue("native-provider", out var providerSize) && providerSize == 64,
        "media runtime provider aggregate failed");

    var quota = await store.GetQuotaSnapshotAsync(41);
    Ensure(quota is { TotalFiles: 2, TotalSizeBytes: 80, MaxStorageSizeBytes: 1000, MaxFileCount: 5 },
        "media runtime quota snapshot failed");
    var usage = await store.GetGroupQuotaUsagesAsync(7);
    Ensure(usage.Count == 1 && usage[0].VirtualKeyGroupName == "native runtime group" &&
        usage[0].TotalFiles == 2 && usage[0].TotalSizeBytes == 80,
        "media runtime group quota reporting failed");
}

static async Task ExerciseAsyncTaskRuntimeStoreAsync(IAsyncTaskRuntimeStore store)
{
    var now = DateTime.UtcNow;
    var task = new AsyncTaskRuntimeRecord
    {
        Id = "native-task",
        Type = "image_generation",
        State = 0,
        CreatedAt = now,
        UpdatedAt = now,
        VirtualKeyId = 1,
        Metadata = "{\"virtualKeyId\":1}",
        MaxRetries = 3,
        IsRetryable = true
    };
    Ensure(await store.CreateAsync(task) == task.Id, "async-task create failed");
    Ensure((await store.GetByIdAsync(task.Id))?.Type == task.Type, "async-task read failed");
    Ensure((await store.GetByStateAsync(0, 1, 100)).TotalCount == 1, "async-task pending query failed");
    Ensure(
        await store.TryClaimTaskAsync(task.Id, "native-worker", TimeSpan.FromMinutes(1)) ==
            AsyncTaskRuntimeClaimStatus.Claimed,
        "async-task claim failed");
    Ensure(
        await store.MarkProviderInvocationStartedAsync(task.Id, "native-worker"),
        "async-task provider start failed");
    Ensure(
        await store.MarkProviderInvocationCompletedAsync(
            task.Id,
            "native-worker",
            "native-operation"),
        "async-task provider completion failed");

    var status = await store.GetByIdAsync(task.Id);
    Ensure(status?.ProviderOperationId == "native-operation", "async-task provider state failed");
    status!.State = 2;
    status.CompletedAt = DateTime.UtcNow.AddDays(-2);
    Ensure(await store.UpdateAsync(status), "async-task update failed");
    Ensure(
        await store.ArchiveOldTasksAsync(TimeSpan.FromDays(1)) == 1,
        "async-task archive failed");
    Ensure(await store.DeleteAsync(task.Id), "async-task delete failed");
}

static async Task ExerciseRequestLogRuntimeStoreAsync(
    NpgsqlDataSource dataSource,
    IRequestLogRuntimeStore store)
{
    var timestamp = new DateTime(2026, 8, 27, 23, 45, 0, DateTimeKind.Utc);
    var id = await store.WriteAsync(new RequestLogRuntimeRecord
    {
        VirtualKeyId = 41,
        ModelName = "native-probe-model",
        ProviderType = "OpenAI",
        PromptCachingEligible = true,
        PromptCachingPolicyApplied = true,
        CachedReadSavings = 0.25m,
        CacheWritePremium = 0.05m,
        RoutingAffinityUsed = true,
        RoutingDecisionReason = "native-probe",
        RoutingFailoverCount = 1,
        RequestType = "chat",
        InputTokens = 100,
        OutputTokens = 25,
        CachedInputTokens = 80,
        CachedWriteTokens = 10,
        Cost = 1.125m,
        BillingMethod = 1,
        ProviderReportedCostUsd = 1m,
        ProviderCostMarkupMultiplier = 1.125m,
        BilledAtUtc = timestamp.AddSeconds(1),
        ResponseTimeMs = 42.5,
        Timestamp = timestamp,
        UserId = "native-user",
        ClientIp = "192.0.2.41",
        RequestPath = "/v1/chat/completions",
        StatusCode = 200,
        MetadataJson = """{"native":true}"""
    });
    Ensure(id > 0, "request-log runtime insert failed");

    await using var connection = await dataSource.OpenConnectionAsync();
    await using var command = connection.CreateCommand();
    command.CommandText = """
        SELECT "VirtualKeyId", "ModelName", "Cost", "BilledAtUtc", "Metadata"->>'native'
        FROM "RequestLogs"
        WHERE "Id" = @id
        """;
    command.Parameters.AddWithValue("id", id);
    await using var reader = await command.ExecuteReaderAsync();
    Ensure(await reader.ReadAsync(), "request-log runtime row lookup failed");
    Ensure(reader.GetInt32(0) == 41, "request-log virtual-key mapping failed");
    Ensure(reader.GetString(1) == "native-probe-model", "request-log model mapping failed");
    Ensure(reader.GetDecimal(2) == 1.125m, "request-log cost mapping failed");
    Ensure(reader.GetFieldValue<DateTime>(3).Kind == DateTimeKind.Utc,
        "request-log UTC mapping failed");
    Ensure(reader.GetString(4) == "true", "request-log JSONB mapping failed");
}

static async Task ExerciseModelRoutingRuntimeStoreAsync(
    NpgsqlDataSource dataSource,
    IModelProviderMappingRuntimeStore store)
{
    await using (var connection = await dataSource.OpenConnectionAsync())
    {
        await ExecuteAsync(connection, $$$"""
            INSERT INTO "Providers" (
                "Id", "ProviderType", "ProviderName", "BaseUrl", "Settings", "IsEnabled",
                "TrustProviderReportedCosts", "ProviderCostMarkupMultiplier", "CreatedAt", "UpdatedAt")
            VALUES (901, {{{(int)ProviderType.OpenRouter}}}, 'native route provider', NULL,
                '{"region":"west"}', true, true, 1.125, now(), now());
            INSERT INTO "ModelSeries" ("Id", "AuthorId", "Name", "Description", "TokenizerType", "Parameters")
            VALUES (902, 1, 'native route series', NULL, 0, '{"temperature":{}}');
            INSERT INTO "Models" (
                "Id", "Name", "Version", "Description", "ModelCardUrl", "ModelSeriesId",
                "SupportsVision", "SupportsImageGeneration", "SupportsVideoGeneration",
                "SupportsEmbeddings", "SupportsSpeechToText", "SupportsTextToSpeech",
                "SupportsRerank", "SupportsChat", "SupportsFunctionCalling", "SupportsStreaming",
                "InputModalities", "OutputModalities", "CapabilitySource",
                "CapabilitiesLastVerifiedAt", "TokenizerType", "MaxInputTokens", "MaxOutputTokens",
                "IsActive", "Parameters", "CreatedAt", "UpdatedAt")
            VALUES (903, 'native route model', 'v1', NULL, NULL, 902,
                true, false, false, false, false, false, false, true, true, true,
                '["text","image"]', '["text"]', 1, now(), 0, 64000, 8192,
                true, NULL, now(), now());
            INSERT INTO "ModelCosts" (
                "Id", "CostName", "PricingModel", "PricingConfiguration",
                "InputCostPerMillionTokens", "OutputCostPerMillionTokens",
                "EmbeddingCostPerMillionTokens", "CreatedAt", "UpdatedAt", "ModelType",
                "IsActive", "EffectiveDate", "ExpiryDate", "Description", "Priority",
                "BatchProcessingMultiplier", "SupportsBatchProcessing",
                "CachedInputCostPerMillionTokens", "CachedInputWriteCostPerMillionTokens",
                "CostPerSearchUnit", "AudioCostPerMinute", "AudioCostPerThousandCharacters",
                "ReasoningCostPerMillionTokens")
            VALUES (904, 'native route cost', 0, NULL, 2.5, 10, NULL, now(), now(), 'chat',
                true, now(), NULL, NULL, 0, 0.5, true, 0.25, NULL, NULL, NULL, NULL, NULL);
            INSERT INTO "ModelIdentifiers" (
                "Id", "ModelId", "IsEnabled", "MaxInputTokens", "MaxOutputTokens",
                "InputModalities", "OutputModalities", "OperationalCapabilities",
                "CapabilitySource", "CapabilitiesLastVerifiedAt", "ProviderVariation",
                "QualityScore", "SpeedScore", "Identifier", "Provider", "ModelCostId",
                "IsPrimary", "Metadata")
            VALUES (905, 903, true, 32000, 4096, '["text"]', '["text"]',
                '{"supports_json_schema":true}', 1, now(), NULL, 0.95, 1.5,
                'provider/native-route', {{{(int)ProviderType.OpenRouter}}}, 904, true, NULL);
            INSERT INTO "ModelProviderMappings" (
                "Id", "ModelAlias", "ProviderModelId", "ProviderId", "IsEnabled",
                "RoutingPriority", "RoutingWeight", "ProviderOptions", "CreatedAt", "UpdatedAt",
                "ModelProviderTypeAssociationId")
            VALUES (906, 'native-route', 'provider/native-route', 901, true,
                10, 1.25, '{"route":"fallback"}', now(), now(), 905);
            INSERT INTO "ModelRoutePolicies" (
                "Id", "ModelAlias", "Strategy", "CostWeight", "SpeedWeight", "QualityWeight",
                "CacheAffinityEnabled", "AffinityTtlSeconds", "MaxAffinityScorePenalty",
                "IsEnabled", "CreatedAt", "UpdatedAt")
            VALUES (907, 'native-route', 'Balanced', 0.5, 0.3, 0.2, true, 900, 0.075,
                true, now(), now());
            """);
    }

    var routes = await store.GetByAliasAsync("NATIVE-ROUTE");
    Ensure(routes.Count == 1 && routes[0].Id == 906, "model-routing alias lookup failed");
    var route = routes[0];
    Ensure(route.Provider.Settings?["region"] == "west", "model-routing provider graph failed");
    Ensure(route.Association.Model.SupportsChat, "model-routing capability graph failed");
    Ensure(route.Association.Model.Series.Name == "native route series",
        "model-routing series graph failed");
    Ensure(route.Association.ModelCost?.InputCostPerMillionTokens == 2.5m,
        "model-routing cost graph failed");
    Ensure((await store.GetByIdAsync(906))?.ProviderModelId == "provider/native-route",
        "model-routing ID lookup failed");
    Ensure((await store.GetPaginatedAsync(1, 10)).TotalCount == 1,
        "model-routing pagination failed");
    Ensure(await store.GetCanonicalModelIdForAssociationAsync(905) == 903,
        "model-routing canonical model lookup failed");
    Ensure((await store.GetModelCostByIdAsync(904))?.OutputCostPerMillionTokens == 10m,
        "model-cost ID lookup failed");
    Ensure((await store.GetModelCostForIdentifierAsync("provider/native-route"))?.Id == 904,
        "model-cost identifier lookup failed");
    var policy = await store.GetRoutePolicyAsync("native-route");
    Ensure(policy is { Strategy: "Balanced", CacheAffinityEnabled: true, AffinityTtlSeconds: 900 },
        "model-routing route policy failed");
}

static void Ensure(bool condition, string message)
{
    if (!condition)
    {
        throw new InvalidOperationException(message);
    }
}
