using System.Text.Json.Serialization;

using ConduitLLM.Admin.DTOs;
using ConduitLLM.Configuration.DTOs;

namespace ConduitLLM.Admin.Serialization;

/// <summary>
/// Source-generated metadata for representative Admin error, list, and operational contracts.
/// </summary>
[JsonSourceGenerationOptions(
    GenerationMode = JsonSourceGenerationMode.Metadata,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
    UseStringEnumConverter = true)]
[JsonSerializable(typeof(AdminProblemDetails))]
[JsonSerializable(typeof(PagedResult<MetricKeyCountDto>))]
[JsonSerializable(typeof(BatchSpendingStatusResponse))]
[JsonSerializable(typeof(BatchSpendingInformationResponse))]
[JsonSerializable(typeof(DiscoveryModelsResponse))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.DTOs.ClearErrorsRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.DTOs.CreateMediaRetentionPolicyRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.DTOs.PruneMediaRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.DTOs.ResolveIndeterminateTaskDto))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.DTOs.RoutePolicyDto))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.DTOs.RoutingDefaultsDto))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.DTOs.UpdateMediaCleanupEnabledRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.DTOs.UpdateMediaRetentionPolicyRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.DTOs.UpdatePromptCachingConfigDto))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.DTOs.UpdateSimpleRetentionRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Endpoints.CreateKeyRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Endpoints.CreateProviderRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Endpoints.PricingSimulationRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Endpoints.PricingValidationRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Endpoints.TestFunctionCredentialRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Endpoints.TestProviderRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Endpoints.UpdateKeyRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Endpoints.UpdateProviderRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Endpoints.ValidatePricingRulesRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Models.ModelAuthors.CreateModelAuthorDto))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Models.ModelAuthors.UpdateModelAuthorDto))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Models.Models.CreateModelDto))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Models.Models.ModelIdentifierRequestDto))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Models.Models.UpdateModelDto))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Models.ModelSeries.CreateModelSeriesDto))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Models.ModelSeries.UpdateModelSeriesDto))]
[JsonSerializable(typeof(global::ConduitLLM.Admin.Models.ProviderSync.BulkDriftActionRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.BulkModelMappingCreateRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.BulkModelMappingPreviewRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.CreateGlobalSettingDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.CreateModelCostDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.CreateModelProviderMappingDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.CreateNotificationDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.CreateProviderToolDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.IpFilter.CreateIpFilterDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.IpFilter.IpFilterSettingsDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.IpFilter.UpdateIpFilterDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.ModelProviderMappingDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.UpdateGlobalSettingDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.UpdateGlobalSettingByKeyDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.UpdateModelCostDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.UpdateModelProviderMappingDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.UpdateNotificationDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.UpdateProviderToolDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.VirtualKey.AdjustBalanceDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.VirtualKey.CreateVirtualKeyGroupRequestDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.VirtualKey.CreateVirtualKeyRequestDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.VirtualKey.ProcessRefundRequestDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.VirtualKey.UpdateVirtualKeyGroupRequestDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.VirtualKey.UpdateVirtualKeyRequestDto))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.DTOs.VirtualKey.ValidateVirtualKeyRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Functions.DTOs.CreateFunctionConfigurationRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Functions.DTOs.CreateFunctionCostDto))]
[JsonSerializable(typeof(global::ConduitLLM.Functions.DTOs.CreateFunctionCredentialRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Functions.DTOs.UpdateFunctionConfigurationRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Functions.DTOs.UpdateFunctionCostDto))]
[JsonSerializable(typeof(global::ConduitLLM.Functions.DTOs.UpdateFunctionCredentialRequest))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.Events.FlushPriority))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.ProviderType))]
[JsonSerializable(typeof(global::ConduitLLM.Configuration.ProviderType?))]
[JsonSerializable(typeof(global::Microsoft.AspNetCore.Http.IFormFile))]
[JsonSerializable(typeof(IEnumerable<global::ConduitLLM.Configuration.DTOs.CreateModelCostDto>))]
[JsonSerializable(typeof(List<global::ConduitLLM.Configuration.DTOs.CreateProviderToolDto>))]
[JsonSerializable(typeof(List<int>))]
public partial class AdminHttpJsonContext : JsonSerializerContext;
