<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\ConduitLLM.Core\OpenApi\*.cs"
             Link="OpenApi\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
