using AwesomeAssertions;

using ConduitLLM.Configuration;
using ConduitLLM.Configuration.Entities;
using ConduitLLM.Configuration.Interfaces;
using ConduitLLM.Configuration.Repositories;
using ConduitLLM.IntegrationTests.Infrastructure;
using ConduitLLM.Persistence.Npgsql;

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;

using Npgsql;

using Xunit;

namespace ConduitLLM.IntegrationTests.Tests;

/// <summary>
/// Runs one behavioral contract against the production EF adapter and the
/// NativeAOT-oriented typed-Npgsql adapter on real PostgreSQL.
/// </summary>
[Collection("Postgres advisory locks")]
public sealed class GlobalSettingRepositoryParityTests
{
    private readonly PostgresLockTestContainerFixture _fixture;

    public GlobalSettingRepositoryParityTests(PostgresLockTestContainerFixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public async Task EfAndTypedNpgsqlImplementTheSameGlobalSettingContract()
    {
        var efSchema = $"global_settings_ef_{Guid.NewGuid():N}";
        var npgsqlSchema = $"global_settings_npgsql_{Guid.NewGuid():N}";

        try
        {
            await CreateSchemaAsync(efSchema);
            await CreateSchemaAsync(npgsqlSchema);

            var efConnectionString = WithSearchPath(efSchema);
            var efRepository = new GlobalSettingRepository(
                new TestDbContextFactory(efConnectionString),
                NullLogger<GlobalSettingRepository>.Instance);
            await ExerciseContractAsync(efRepository);

            var npgsqlConnectionString = WithSearchPath(npgsqlSchema);
            await using var dataSource = NpgsqlDataSource.Create(npgsqlConnectionString);
            var npgsqlRepository = new NpgsqlGlobalSettingRepository(dataSource);
            await ExerciseContractAsync(npgsqlRepository);
        }
        finally
        {
            await DropSchemaAsync(efSchema);
            await DropSchemaAsync(npgsqlSchema);
        }
    }

    private static async Task ExerciseContractAsync(IGlobalSettingRepository repository)
    {
        (await repository.ListAsync()).Should().BeEmpty();

        var beta = new GlobalSetting
        {
            Key = "beta",
            Value = "one",
            Description = "initial",
            CreatedAt = default
        };
        var betaId = await repository.CreateAsync(beta);
        betaId.Should().BeGreaterThan(0);
        beta.Id.Should().Be(betaId);

        var byId = await repository.GetByIdAsync(betaId);
        byId.Should().NotBeNull();
        byId!.Key.Should().Be("beta");
        byId.Value.Should().Be("one");
        byId.Description.Should().Be("initial");
        byId.CreatedAt.Kind.Should().Be(DateTimeKind.Utc);
        byId.UpdatedAt.Kind.Should().Be(DateTimeKind.Utc);

        byId.Value = "two";
        byId.Description = null;
        (await repository.UpdateAsync(byId)).Should().BeTrue();
        (await repository.GetByKeyAsync("beta"))!.Description.Should().BeNull();

        (await repository.UpsertAsync("beta", "three", "restored")).Should().BeTrue();
        (await repository.UpsertAsync("beta", "four")).Should().BeTrue();
        var afterUpsert = await repository.GetByKeyAsync("beta");
        afterUpsert!.Value.Should().Be("four");
        afterUpsert.Description.Should().Be("restored");

        (await repository.UpsertAsync("alpha", "first", "created by upsert")).Should().BeTrue();
        var settings = await repository.ListAsync();
        settings.Select(setting => setting.Key).Should().Equal("alpha", "beta");

        (await repository.DeleteAsync(-1)).Should().BeFalse();
        (await repository.DeleteByKeyAsync("missing")).Should().BeFalse();
        (await repository.DeleteAsync(betaId)).Should().BeTrue();
        (await repository.DeleteByKeyAsync("alpha")).Should().BeTrue();
        (await repository.ListAsync()).Should().BeEmpty();

        await Assert.ThrowsAsync<ArgumentException>(() => repository.GetByKeyAsync(string.Empty));
        await Assert.ThrowsAsync<ArgumentException>(() => repository.UpsertAsync(string.Empty, "value"));
    }

    private async Task CreateSchemaAsync(string schema)
    {
        await using var connection = new NpgsqlConnection(_fixture.ConnectionString);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = $"""
            CREATE SCHEMA "{schema}";
            CREATE TABLE "{schema}"."GlobalSettings" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Key" character varying(100) NOT NULL,
                "Value" character varying(2000) NOT NULL,
                "Description" character varying(500) NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "UQ_{schema}_GlobalSettings_Key" UNIQUE ("Key")
            );
            """;
        await command.ExecuteNonQueryAsync();
    }

    private async Task DropSchemaAsync(string schema)
    {
        await using var connection = new NpgsqlConnection(_fixture.ConnectionString);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = $"DROP SCHEMA IF EXISTS \"{schema}\" CASCADE";
        await command.ExecuteNonQueryAsync();
    }

    private string WithSearchPath(string schema)
    {
        var builder = new NpgsqlConnectionStringBuilder(_fixture.ConnectionString)
        {
            SearchPath = schema
        };
        return builder.ConnectionString;
    }

    private sealed class TestDbContextFactory(string connectionString) :
        IDbContextFactory<ConduitDbContext>
    {
        private readonly DbContextOptions<ConduitDbContext> _options =
            new DbContextOptionsBuilder<ConduitDbContext>()
                .UseNpgsql(connectionString)
                .Options;

        public ConduitDbContext CreateDbContext() => new(_options);

        public Task<ConduitDbContext> CreateDbContextAsync(
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return Task.FromResult(CreateDbContext());
        }
    }
}
