using AwesomeAssertions;

using System.Text.Json;

using ConduitLLM.Configuration;
using ConduitLLM.Configuration.Repositories;
using ConduitLLM.IntegrationTests.Infrastructure;
using ConduitLLM.Persistence;
using ConduitLLM.Persistence.Interfaces;
using ConduitLLM.Persistence.Npgsql;

using Microsoft.EntityFrameworkCore;

using Npgsql;

using Xunit;

namespace ConduitLLM.IntegrationTests.Tests;

/// <summary>
/// Runs the Gateway request-accounting write contract against EF and typed Npgsql.
/// </summary>
[Collection("Postgres advisory locks")]
public sealed class RequestLogRuntimePersistenceParityTests
{
    private readonly PostgresLockTestContainerFixture _fixture;

    public RequestLogRuntimePersistenceParityTests(PostgresLockTestContainerFixture fixture)
    {
        _fixture = fixture;
    }

    [Fact]
    public async Task EfAndTypedNpgsqlWriteTheSameRequestLogRow()
    {
        var efSchema = $"request_log_ef_{Guid.NewGuid():N}";
        var npgsqlSchema = $"request_log_np_{Guid.NewGuid():N}";
        var timestamp = new DateTime(2026, 8, 27, 22, 15, 30, DateTimeKind.Utc);
        var record = new RequestLogRuntimeRecord
        {
            VirtualKeyId = 41,
            ModelName = "gpt-native",
            ProviderId = 12,
            ProviderType = "OpenAI",
            ModelProviderMappingId = 77,
            PromptCachingEligible = true,
            PromptCachingPolicyApplied = true,
            CachedReadSavings = 0.12345678m,
            CacheWritePremium = 0.01234567m,
            RoutingAffinityUsed = true,
            RoutingDecisionReason = "cache-affinity",
            RoutingFailoverCount = 2,
            RequestType = "chat",
            InputTokens = 101,
            OutputTokens = 37,
            CachedInputTokens = 80,
            CachedWriteTokens = 11,
            Cost = 1.234567m,
            BillingMethod = 1,
            ProviderReportedCostUsd = 1.11111111m,
            ProviderCostMarkupMultiplier = 1.125m,
            BilledAtUtc = timestamp.AddSeconds(1),
            ResponseTimeMs = 42.75,
            Timestamp = timestamp,
            UserId = "user-1",
            ClientIp = "192.0.2.10",
            RequestPath = "/v1/chat/completions",
            StatusCode = 200,
            MetadataJson = """{"tenant":"acme","stream":true}"""
        };

        try
        {
            await CreateSchemaAsync(efSchema);
            await CreateSchemaAsync(npgsqlSchema);

            var efId = await ExerciseContractAsync(
                new EfRequestLogRuntimeStore(new TestDbContextFactory(WithSearchPath(efSchema))),
                record);
            await using var dataSource = NpgsqlDataSource.Create(WithSearchPath(npgsqlSchema));
            var npgsqlId = await ExerciseContractAsync(
                new NpgsqlRequestLogRuntimeStore(dataSource),
                record);

            efId.Should().BePositive();
            npgsqlId.Should().BePositive();
            using var efRow = JsonDocument.Parse(await ReadRowAsJsonAsync(efSchema));
            using var npgsqlRow = JsonDocument.Parse(await ReadRowAsJsonAsync(npgsqlSchema));
            JsonElement.DeepEquals(efRow.RootElement, npgsqlRow.RootElement).Should().BeTrue();
        }
        finally
        {
            await DropSchemaAsync(efSchema);
            await DropSchemaAsync(npgsqlSchema);
        }
    }

    private static async Task<int> ExerciseContractAsync(
        IRequestLogRuntimeStore store,
        RequestLogRuntimeRecord record)
    {
        using var cancellation = new CancellationTokenSource();
        return await store.WriteAsync(record, cancellation.Token);
    }

    private async Task CreateSchemaAsync(string schema)
    {
        await using var connection = new NpgsqlConnection(_fixture.ConnectionString);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = $"""
            CREATE SCHEMA "{schema}";
            CREATE TABLE "{schema}"."RequestLogs" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "VirtualKeyId" integer NOT NULL,
                "ModelName" character varying(100) NOT NULL,
                "ProviderId" integer NULL,
                "ProviderType" character varying(50) NULL,
                "ModelProviderMappingId" integer NULL,
                "PromptCachingEligible" boolean NOT NULL,
                "PromptCachingPolicyApplied" boolean NOT NULL,
                "CachedReadSavings" numeric(18,8) NOT NULL,
                "CacheWritePremium" numeric(18,8) NOT NULL,
                "RoutingAffinityUsed" boolean NOT NULL,
                "RoutingDecisionReason" character varying(50) NULL,
                "RoutingFailoverCount" integer NOT NULL,
                "RequestType" character varying(50) NOT NULL,
                "InputTokens" integer NOT NULL,
                "OutputTokens" integer NOT NULL,
                "CachedInputTokens" integer NULL,
                "CachedWriteTokens" integer NULL,
                "Cost" numeric(10,6) NOT NULL,
                "BillingMethod" integer NULL,
                "ProviderReportedCostUsd" numeric(18,8) NULL,
                "ProviderCostMarkupMultiplier" numeric(18,8) NULL,
                "BilledAtUtc" timestamp with time zone NULL,
                "ResponseTimeMs" double precision NOT NULL,
                "Timestamp" timestamp with time zone NOT NULL,
                "UserId" character varying(100) NULL,
                "ClientIp" character varying(50) NULL,
                "RequestPath" character varying(256) NULL,
                "StatusCode" integer NULL,
                "Metadata" jsonb NULL
            );
            """;
        await command.ExecuteNonQueryAsync();
    }

    private async Task<string> ReadRowAsJsonAsync(string schema)
    {
        await using var connection = new NpgsqlConnection(_fixture.ConnectionString);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = $"SELECT (to_jsonb(row) - 'Id')::text FROM \"{schema}\".\"RequestLogs\" row";
        return (string)(await command.ExecuteScalarAsync())!;
    }

    private async Task DropSchemaAsync(string schema)
    {
        await using var connection = new NpgsqlConnection(_fixture.ConnectionString);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = $"DROP SCHEMA IF EXISTS \"{schema}\" CASCADE";
        await command.ExecuteNonQueryAsync();
    }

    private string WithSearchPath(string schema)
    {
        return new NpgsqlConnectionStringBuilder(_fixture.ConnectionString)
        {
            SearchPath = schema
        }.ConnectionString;
    }

    private sealed class TestDbContextFactory(string connectionString) :
        IDbContextFactory<ConduitDbContext>
    {
        private readonly DbContextOptions<ConduitDbContext> _options =
            new DbContextOptionsBuilder<ConduitDbContext>()
                .UseNpgsql(connectionString)
                .Options;

        public ConduitDbContext CreateDbContext() => new(_options);

        public Task<ConduitDbContext> CreateDbContextAsync(
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return Task.FromResult(CreateDbContext());
        }
    }
}
