// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using ConduitLLM.Configuration.Entities;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class BillingReconciliationCheckpointEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "ConduitLLM.Configuration.Entities.BillingReconciliationCheckpoint",
                typeof(BillingReconciliationCheckpoint),
                baseEntityType,
                propertyCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(BillingReconciliationCheckpoint).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BillingReconciliationCheckpoint).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (BillingReconciliationCheckpoint instance) => BillingReconciliationCheckpointUnsafeAccessors.Id(instance),
                bool (BillingReconciliationCheckpoint instance) => BillingReconciliationCheckpointUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                BillingReconciliationCheckpoint (BillingReconciliationCheckpoint instance, int value) =>
                {
                    BillingReconciliationCheckpointUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                BillingReconciliationCheckpoint (BillingReconciliationCheckpoint instance, int value) =>
                {
                    BillingReconciliationCheckpointUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && BillingReconciliationCheckpointUnsafeAccessors.Id(((BillingReconciliationCheckpoint)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : BillingReconciliationCheckpointUnsafeAccessors.Id(((BillingReconciliationCheckpoint)(entry.Entity))))),
                int (IInternalEntry entry) => BillingReconciliationCheckpointUnsafeAccessors.Id(((BillingReconciliationCheckpoint)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            var nextWindowStartUtc = runtimeEntityType.AddProperty(
                "NextWindowStartUtc",
                typeof(DateTime),
                propertyInfo: typeof(BillingReconciliationCheckpoint).GetProperty("NextWindowStartUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BillingReconciliationCheckpoint).GetField("<NextWindowStartUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            nextWindowStartUtc.SetGetter(
                DateTime (BillingReconciliationCheckpoint instance) => BillingReconciliationCheckpointUnsafeAccessors.NextWindowStartUtc(instance),
                bool (BillingReconciliationCheckpoint instance) => BillingReconciliationCheckpointUnsafeAccessors.NextWindowStartUtc(instance) == default(DateTime));
            nextWindowStartUtc.SetSetter(
                BillingReconciliationCheckpoint (BillingReconciliationCheckpoint instance, DateTime value) =>
                {
                    BillingReconciliationCheckpointUnsafeAccessors.NextWindowStartUtc(instance) = value;
                    return instance;
                });
            nextWindowStartUtc.SetMaterializationSetter(
                BillingReconciliationCheckpoint (BillingReconciliationCheckpoint instance, DateTime value) =>
                {
                    BillingReconciliationCheckpointUnsafeAccessors.NextWindowStartUtc(instance) = value;
                    return instance;
                });
            nextWindowStartUtc.SetAccessors(
                DateTime (IInternalEntry entry) => BillingReconciliationCheckpointUnsafeAccessors.NextWindowStartUtc(((BillingReconciliationCheckpoint)(entry.Entity))),
                DateTime (IInternalEntry entry) => BillingReconciliationCheckpointUnsafeAccessors.NextWindowStartUtc(((BillingReconciliationCheckpoint)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(nextWindowStartUtc, 1),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(nextWindowStartUtc));
            nextWindowStartUtc.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            nextWindowStartUtc.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                keyComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                providerValueComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v));
            nextWindowStartUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var updatedAtUtc = runtimeEntityType.AddProperty(
                "UpdatedAtUtc",
                typeof(DateTime),
                propertyInfo: typeof(BillingReconciliationCheckpoint).GetProperty("UpdatedAtUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BillingReconciliationCheckpoint).GetField("<UpdatedAtUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            updatedAtUtc.SetGetter(
                DateTime (BillingReconciliationCheckpoint instance) => BillingReconciliationCheckpointUnsafeAccessors.UpdatedAtUtc(instance),
                bool (BillingReconciliationCheckpoint instance) => BillingReconciliationCheckpointUnsafeAccessors.UpdatedAtUtc(instance) == default(DateTime));
            updatedAtUtc.SetSetter(
                BillingReconciliationCheckpoint (BillingReconciliationCheckpoint instance, DateTime value) =>
                {
                    BillingReconciliationCheckpointUnsafeAccessors.UpdatedAtUtc(instance) = value;
                    return instance;
                });
            updatedAtUtc.SetMaterializationSetter(
                BillingReconciliationCheckpoint (BillingReconciliationCheckpoint instance, DateTime value) =>
                {
                    BillingReconciliationCheckpointUnsafeAccessors.UpdatedAtUtc(instance) = value;
                    return instance;
                });
            updatedAtUtc.SetAccessors(
                DateTime (IInternalEntry entry) => BillingReconciliationCheckpointUnsafeAccessors.UpdatedAtUtc(((BillingReconciliationCheckpoint)(entry.Entity))),
                DateTime (IInternalEntry entry) => BillingReconciliationCheckpointUnsafeAccessors.UpdatedAtUtc(((BillingReconciliationCheckpoint)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(updatedAtUtc, 2),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(updatedAtUtc));
            updatedAtUtc.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            updatedAtUtc.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                keyComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                providerValueComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v));
            updatedAtUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var nextWindowStartUtc = runtimeEntityType.FindProperty("NextWindowStartUtc");
            var updatedAtUtc = runtimeEntityType.FindProperty("UpdatedAtUtc");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((BillingReconciliationCheckpoint)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, DateTime, DateTime>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<DateTime>)(((IProperty)nextWindowStartUtc).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(nextWindowStartUtc)), ((ValueComparer<DateTime>)(((IProperty)updatedAtUtc).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(updatedAtUtc)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int>(default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((BillingReconciliationCheckpoint)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 3,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 3,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "BillingReconciliationCheckpoints");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
