// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using ConduitLLM.Functions.Entities;
using ConduitLLM.Functions.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class FunctionCredentialEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "ConduitLLM.Functions.Entities.FunctionCredential",
                typeof(FunctionCredential),
                baseEntityType,
                propertyCount: 12,
                foreignKeyCount: 1,
                unnamedIndexCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(FunctionCredential).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FunctionCredential).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.Id(instance),
                bool (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                FunctionCredential (FunctionCredential instance, int value) =>
                {
                    FunctionCredentialUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                FunctionCredential (FunctionCredential instance, int value) =>
                {
                    FunctionCredentialUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && FunctionCredentialUnsafeAccessors.Id(((FunctionCredential)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : FunctionCredentialUnsafeAccessors.Id(((FunctionCredential)(entry.Entity))))),
                int (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.Id(((FunctionCredential)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            var apiKey = runtimeEntityType.AddProperty(
                "ApiKey",
                typeof(string),
                propertyInfo: typeof(FunctionCredential).GetProperty("ApiKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FunctionCredential).GetField("<ApiKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            apiKey.SetGetter(
                string (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.ApiKey(instance),
                bool (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.ApiKey(instance) == null);
            apiKey.SetSetter(
                FunctionCredential (FunctionCredential instance, string value) =>
                {
                    FunctionCredentialUnsafeAccessors.ApiKey(instance) = value;
                    return instance;
                });
            apiKey.SetMaterializationSetter(
                FunctionCredential (FunctionCredential instance, string value) =>
                {
                    FunctionCredentialUnsafeAccessors.ApiKey(instance) = value;
                    return instance;
                });
            apiKey.SetAccessors(
                string (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.ApiKey(((FunctionCredential)(entry.Entity))),
                string (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.ApiKey(((FunctionCredential)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(apiKey, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(apiKey));
            apiKey.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            apiKey.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(2000)",
                    size: 2000));
            apiKey.TypeMapping = ((NpgsqlStringTypeMapping)apiKey.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        apiKey.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(apiKey));
        apiKey.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var baseUrl = runtimeEntityType.AddProperty(
            "BaseUrl",
            typeof(string),
            propertyInfo: typeof(FunctionCredential).GetProperty("BaseUrl", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(FunctionCredential).GetField("<BaseUrl>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            nullable: true,
            maxLength: 500);
        baseUrl.SetGetter(
            string (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.BaseUrl(instance),
            bool (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.BaseUrl(instance) == null);
        baseUrl.SetSetter(
            FunctionCredential (FunctionCredential instance, string value) =>
            {
                FunctionCredentialUnsafeAccessors.BaseUrl(instance) = value;
                return instance;
            });
        baseUrl.SetMaterializationSetter(
            FunctionCredential (FunctionCredential instance, string value) =>
            {
                FunctionCredentialUnsafeAccessors.BaseUrl(instance) = value;
                return instance;
            });
        baseUrl.SetAccessors(
            string (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.BaseUrl(((FunctionCredential)(entry.Entity))),
            string (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.BaseUrl(((FunctionCredential)(entry.Entity))),
            string (IInternalEntry entry) => entry.ReadOriginalValue<string>(baseUrl, 2),
            string (IInternalEntry entry) => entry.GetCurrentValue<string>(baseUrl));
        baseUrl.SetPropertyIndexes(
            index: 2,
            originalValueIndex: 2,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        baseUrl.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
            comparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            keyComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            providerValueComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "character varying(500)",
                size: 500));
        baseUrl.TypeMapping = ((NpgsqlStringTypeMapping)baseUrl.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
    baseUrl.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var createdAt = runtimeEntityType.AddProperty(
        "CreatedAt",
        typeof(DateTime),
        propertyInfo: typeof(FunctionCredential).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(FunctionCredential).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
    createdAt.SetGetter(
        DateTime (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.CreatedAt(instance),
        bool (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.CreatedAt(instance) == default(DateTime));
    createdAt.SetSetter(
        FunctionCredential (FunctionCredential instance, DateTime value) =>
        {
            FunctionCredentialUnsafeAccessors.CreatedAt(instance) = value;
            return instance;
        });
    createdAt.SetMaterializationSetter(
        FunctionCredential (FunctionCredential instance, DateTime value) =>
        {
            FunctionCredentialUnsafeAccessors.CreatedAt(instance) = value;
            return instance;
        });
    createdAt.SetAccessors(
        DateTime (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.CreatedAt(((FunctionCredential)(entry.Entity))),
        DateTime (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.CreatedAt(((FunctionCredential)(entry.Entity))),
        DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(createdAt, 3),
        DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(createdAt));
    createdAt.SetPropertyIndexes(
        index: 3,
        originalValueIndex: 3,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    createdAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
        comparer: new ValueComparer<DateTime>(
            bool (DateTime v1, DateTime v2) => v1.Equals(v2),
            int (DateTime v) => ((object)v).GetHashCode(),
            DateTime (DateTime v) => v),
        keyComparer: new ValueComparer<DateTime>(
            bool (DateTime v1, DateTime v2) => v1.Equals(v2),
            int (DateTime v) => ((object)v).GetHashCode(),
            DateTime (DateTime v) => v),
        providerValueComparer: new ValueComparer<DateTime>(
            bool (DateTime v1, DateTime v2) => v1.Equals(v2),
            int (DateTime v) => ((object)v).GetHashCode(),
            DateTime (DateTime v) => v));
    createdAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var functionAccountGroup = runtimeEntityType.AddProperty(
        "FunctionAccountGroup",
        typeof(short),
        propertyInfo: typeof(FunctionCredential).GetProperty("FunctionAccountGroup", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(FunctionCredential).GetField("<FunctionAccountGroup>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        sentinel: (short)0);
    functionAccountGroup.SetGetter(
        short (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.FunctionAccountGroup(instance),
        bool (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.FunctionAccountGroup(instance) == 0);
    functionAccountGroup.SetSetter(
        FunctionCredential (FunctionCredential instance, short value) =>
        {
            FunctionCredentialUnsafeAccessors.FunctionAccountGroup(instance) = value;
            return instance;
        });
    functionAccountGroup.SetMaterializationSetter(
        FunctionCredential (FunctionCredential instance, short value) =>
        {
            FunctionCredentialUnsafeAccessors.FunctionAccountGroup(instance) = value;
            return instance;
        });
    functionAccountGroup.SetAccessors(
        short (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.FunctionAccountGroup(((FunctionCredential)(entry.Entity))),
        short (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.FunctionAccountGroup(((FunctionCredential)(entry.Entity))),
        short (IInternalEntry entry) => entry.ReadOriginalValue<short>(functionAccountGroup, 4),
        short (IInternalEntry entry) => entry.GetCurrentValue<short>(functionAccountGroup));
    functionAccountGroup.SetPropertyIndexes(
        index: 4,
        originalValueIndex: 4,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    functionAccountGroup.TypeMapping = ShortTypeMapping.Default.Clone(
        comparer: new ValueComparer<short>(
            bool (short v1, short v2) => v1 == v2,
            int (short v) => ((int)v),
            short (short v) => v),
        keyComparer: new ValueComparer<short>(
            bool (short v1, short v2) => v1 == v2,
            int (short v) => ((int)v),
            short (short v) => v),
        providerValueComparer: new ValueComparer<short>(
            bool (short v1, short v2) => v1 == v2,
            int (short v) => ((int)v),
            short (short v) => v));
    functionAccountGroup.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var functionConfigurationId = runtimeEntityType.AddProperty(
        "FunctionConfigurationId",
        typeof(int?),
        propertyInfo: typeof(FunctionCredential).GetProperty("FunctionConfigurationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(FunctionCredential).GetField("<FunctionConfigurationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        nullable: true);
    functionConfigurationId.SetGetter(
        int? (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.FunctionConfigurationId(instance),
        bool (FunctionCredential instance) => !(FunctionCredentialUnsafeAccessors.FunctionConfigurationId(instance).HasValue));
    functionConfigurationId.SetSetter(
        FunctionCredential (FunctionCredential instance, int? value) =>
        {
            FunctionCredentialUnsafeAccessors.FunctionConfigurationId(instance) = value;
            return instance;
        });
    functionConfigurationId.SetMaterializationSetter(
        FunctionCredential (FunctionCredential instance, int? value) =>
        {
            FunctionCredentialUnsafeAccessors.FunctionConfigurationId(instance) = value;
            return instance;
        });
    functionConfigurationId.SetAccessors(
        int? (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(5) ? entry.ReadStoreGeneratedValue<int?>(1) : (entry.FlaggedAsTemporary(5) && !(FunctionCredentialUnsafeAccessors.FunctionConfigurationId(((FunctionCredential)(entry.Entity))).HasValue) ? entry.ReadTemporaryValue<int?>(1) : FunctionCredentialUnsafeAccessors.FunctionConfigurationId(((FunctionCredential)(entry.Entity))))),
        int? (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.FunctionConfigurationId(((FunctionCredential)(entry.Entity))),
        int? (IInternalEntry entry) => entry.ReadOriginalValue<int?>(functionConfigurationId, 5),
        int? (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int?>(functionConfigurationId, 1));
    functionConfigurationId.SetPropertyIndexes(
        index: 5,
        originalValueIndex: 5,
        shadowIndex: -1,
        relationshipIndex: 1,
        storeGenerationIndex: 1);
    functionConfigurationId.TypeMapping = IntTypeMapping.Default.Clone(
        comparer: new ValueComparer<int>(
            bool (int v1, int v2) => v1 == v2,
            int (int v) => v,
            int (int v) => v),
        keyComparer: new ValueComparer<int>(
            bool (int v1, int v2) => v1 == v2,
            int (int v) => v,
            int (int v) => v),
        providerValueComparer: new ValueComparer<int>(
            bool (int v1, int v2) => v1 == v2,
            int (int v) => v,
            int (int v) => v),
        mappingInfo: new RelationalTypeMappingInfo(
            storeTypeName: "integer"));
    functionConfigurationId.SetCurrentValueComparer(new EntryCurrentValueComparer<int?>(functionConfigurationId));
    functionConfigurationId.SetComparer(new NullableValueComparer<int>(functionConfigurationId.TypeMapping.Comparer));
    functionConfigurationId.SetKeyComparer(new NullableValueComparer<int>(functionConfigurationId.TypeMapping.KeyComparer));
    functionConfigurationId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var isEnabled = runtimeEntityType.AddProperty(
        "IsEnabled",
        typeof(bool),
        propertyInfo: typeof(FunctionCredential).GetProperty("IsEnabled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(FunctionCredential).GetField("<IsEnabled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        sentinel: false);
    isEnabled.SetGetter(
        bool (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.IsEnabled(instance),
        bool (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.IsEnabled(instance) == false);
    isEnabled.SetSetter(
        FunctionCredential (FunctionCredential instance, bool value) =>
        {
            FunctionCredentialUnsafeAccessors.IsEnabled(instance) = value;
            return instance;
        });
    isEnabled.SetMaterializationSetter(
        FunctionCredential (FunctionCredential instance, bool value) =>
        {
            FunctionCredentialUnsafeAccessors.IsEnabled(instance) = value;
            return instance;
        });
    isEnabled.SetAccessors(
        bool (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.IsEnabled(((FunctionCredential)(entry.Entity))),
        bool (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.IsEnabled(((FunctionCredential)(entry.Entity))),
        bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isEnabled, 6),
        bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isEnabled));
    isEnabled.SetPropertyIndexes(
        index: 6,
        originalValueIndex: 6,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    isEnabled.TypeMapping = NpgsqlBoolTypeMapping.Default.Clone(
        comparer: new ValueComparer<bool>(
            bool (bool v1, bool v2) => v1 == v2,
            int (bool v) => ((object)v).GetHashCode(),
            bool (bool v) => v),
        keyComparer: new ValueComparer<bool>(
            bool (bool v1, bool v2) => v1 == v2,
            int (bool v) => ((object)v).GetHashCode(),
            bool (bool v) => v),
        providerValueComparer: new ValueComparer<bool>(
            bool (bool v1, bool v2) => v1 == v2,
            int (bool v) => ((object)v).GetHashCode(),
            bool (bool v) => v));
    isEnabled.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var isPrimary = runtimeEntityType.AddProperty(
        "IsPrimary",
        typeof(bool),
        propertyInfo: typeof(FunctionCredential).GetProperty("IsPrimary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(FunctionCredential).GetField("<IsPrimary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        sentinel: false);
    isPrimary.SetGetter(
        bool (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.IsPrimary(instance),
        bool (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.IsPrimary(instance) == false);
    isPrimary.SetSetter(
        FunctionCredential (FunctionCredential instance, bool value) =>
        {
            FunctionCredentialUnsafeAccessors.IsPrimary(instance) = value;
            return instance;
        });
    isPrimary.SetMaterializationSetter(
        FunctionCredential (FunctionCredential instance, bool value) =>
        {
            FunctionCredentialUnsafeAccessors.IsPrimary(instance) = value;
            return instance;
        });
    isPrimary.SetAccessors(
        bool (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.IsPrimary(((FunctionCredential)(entry.Entity))),
        bool (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.IsPrimary(((FunctionCredential)(entry.Entity))),
        bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isPrimary, 7),
        bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isPrimary));
    isPrimary.SetPropertyIndexes(
        index: 7,
        originalValueIndex: 7,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    isPrimary.TypeMapping = NpgsqlBoolTypeMapping.Default.Clone(
        comparer: new ValueComparer<bool>(
            bool (bool v1, bool v2) => v1 == v2,
            int (bool v) => ((object)v).GetHashCode(),
            bool (bool v) => v),
        keyComparer: new ValueComparer<bool>(
            bool (bool v1, bool v2) => v1 == v2,
            int (bool v) => ((object)v).GetHashCode(),
            bool (bool v) => v),
        providerValueComparer: new ValueComparer<bool>(
            bool (bool v1, bool v2) => v1 == v2,
            int (bool v) => ((object)v).GetHashCode(),
            bool (bool v) => v));
    isPrimary.SetCurrentValueComparer(new EntryCurrentValueComparer<bool>(isPrimary));
    isPrimary.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var keyName = runtimeEntityType.AddProperty(
        "KeyName",
        typeof(string),
        propertyInfo: typeof(FunctionCredential).GetProperty("KeyName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(FunctionCredential).GetField("<KeyName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        nullable: true,
        maxLength: 200);
    keyName.SetGetter(
        string (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.KeyName(instance),
        bool (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.KeyName(instance) == null);
    keyName.SetSetter(
        FunctionCredential (FunctionCredential instance, string value) =>
        {
            FunctionCredentialUnsafeAccessors.KeyName(instance) = value;
            return instance;
        });
    keyName.SetMaterializationSetter(
        FunctionCredential (FunctionCredential instance, string value) =>
        {
            FunctionCredentialUnsafeAccessors.KeyName(instance) = value;
            return instance;
        });
    keyName.SetAccessors(
        string (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.KeyName(((FunctionCredential)(entry.Entity))),
        string (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.KeyName(((FunctionCredential)(entry.Entity))),
        string (IInternalEntry entry) => entry.ReadOriginalValue<string>(keyName, 8),
        string (IInternalEntry entry) => entry.GetCurrentValue<string>(keyName));
    keyName.SetPropertyIndexes(
        index: 8,
        originalValueIndex: 8,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    keyName.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
        comparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        keyComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        providerValueComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        mappingInfo: new RelationalTypeMappingInfo(
            storeTypeName: "character varying(200)",
            size: 200));
    keyName.TypeMapping = ((NpgsqlStringTypeMapping)keyName.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
keyName.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var organization = runtimeEntityType.AddProperty(
    "Organization",
    typeof(string),
    propertyInfo: typeof(FunctionCredential).GetProperty("Organization", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(FunctionCredential).GetField("<Organization>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    nullable: true,
    maxLength: 200);
organization.SetGetter(
    string (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.Organization(instance),
    bool (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.Organization(instance) == null);
organization.SetSetter(
    FunctionCredential (FunctionCredential instance, string value) =>
    {
        FunctionCredentialUnsafeAccessors.Organization(instance) = value;
        return instance;
    });
organization.SetMaterializationSetter(
    FunctionCredential (FunctionCredential instance, string value) =>
    {
        FunctionCredentialUnsafeAccessors.Organization(instance) = value;
        return instance;
    });
organization.SetAccessors(
    string (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.Organization(((FunctionCredential)(entry.Entity))),
    string (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.Organization(((FunctionCredential)(entry.Entity))),
    string (IInternalEntry entry) => entry.ReadOriginalValue<string>(organization, 9),
    string (IInternalEntry entry) => entry.GetCurrentValue<string>(organization));
organization.SetPropertyIndexes(
    index: 9,
    originalValueIndex: 9,
    shadowIndex: -1,
    relationshipIndex: -1,
    storeGenerationIndex: -1);
organization.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
    comparer: new ValueComparer<string>(
        bool (string v1, string v2) => v1 == v2,
        int (string v) => ((object)v).GetHashCode(),
        string (string v) => v),
    keyComparer: new ValueComparer<string>(
        bool (string v1, string v2) => v1 == v2,
        int (string v) => ((object)v).GetHashCode(),
        string (string v) => v),
    providerValueComparer: new ValueComparer<string>(
        bool (string v1, string v2) => v1 == v2,
        int (string v) => ((object)v).GetHashCode(),
        string (string v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "character varying(200)",
        size: 200));
organization.TypeMapping = ((NpgsqlStringTypeMapping)organization.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
organization.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var providerType = runtimeEntityType.AddProperty(
    "ProviderType",
    typeof(FunctionProviderType),
    propertyInfo: typeof(FunctionCredential).GetProperty("ProviderType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(FunctionCredential).GetField("<ProviderType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
providerType.SetGetter(
    FunctionProviderType (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.ProviderType(instance),
    bool (FunctionCredential instance) => object.Equals(((object)(FunctionCredentialUnsafeAccessors.ProviderType(instance))), ((object)((FunctionProviderType)0L))));
providerType.SetSetter(
    FunctionCredential (FunctionCredential instance, FunctionProviderType value) =>
    {
        FunctionCredentialUnsafeAccessors.ProviderType(instance) = value;
        return instance;
    });
providerType.SetMaterializationSetter(
    FunctionCredential (FunctionCredential instance, FunctionProviderType value) =>
    {
        FunctionCredentialUnsafeAccessors.ProviderType(instance) = value;
        return instance;
    });
providerType.SetAccessors(
    FunctionProviderType (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.ProviderType(((FunctionCredential)(entry.Entity))),
    FunctionProviderType (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.ProviderType(((FunctionCredential)(entry.Entity))),
    FunctionProviderType (IInternalEntry entry) => entry.ReadOriginalValue<FunctionProviderType>(providerType, 10),
    FunctionProviderType (IInternalEntry entry) => entry.GetCurrentValue<FunctionProviderType>(providerType));
providerType.SetPropertyIndexes(
    index: 10,
    originalValueIndex: 10,
    shadowIndex: -1,
    relationshipIndex: -1,
    storeGenerationIndex: -1);
providerType.TypeMapping = IntTypeMapping.Default.Clone(
    comparer: new ValueComparer<FunctionProviderType>(
        bool (FunctionProviderType v1, FunctionProviderType v2) => object.Equals(((object)v1), ((object)v2)),
        int (FunctionProviderType v) => ((object)v).GetHashCode(),
        FunctionProviderType (FunctionProviderType v) => v),
    keyComparer: new ValueComparer<FunctionProviderType>(
        bool (FunctionProviderType v1, FunctionProviderType v2) => object.Equals(((object)v1), ((object)v2)),
        int (FunctionProviderType v) => ((object)v).GetHashCode(),
        FunctionProviderType (FunctionProviderType v) => v),
    providerValueComparer: new ValueComparer<int>(
        bool (int v1, int v2) => v1 == v2,
        int (int v) => v,
        int (int v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "integer"),
    converter: new ValueConverter<FunctionProviderType, int>(
        int (FunctionProviderType value) => ((int)value),
        FunctionProviderType (int value) => ((FunctionProviderType)value)),
    jsonValueReaderWriter: new JsonConvertedValueReaderWriter<FunctionProviderType, int>(
        JsonInt32ReaderWriter.Instance,
        new ValueConverter<FunctionProviderType, int>(
            int (FunctionProviderType value) => ((int)value),
            FunctionProviderType (int value) => ((FunctionProviderType)value))));
providerType.SetCurrentValueComparer(new EntryCurrentValueComparer<FunctionProviderType>(providerType));
providerType.SetSentinelFromProviderValue(0);
providerType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var updatedAt = runtimeEntityType.AddProperty(
    "UpdatedAt",
    typeof(DateTime),
    propertyInfo: typeof(FunctionCredential).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(FunctionCredential).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
updatedAt.SetGetter(
    DateTime (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.UpdatedAt(instance),
    bool (FunctionCredential instance) => FunctionCredentialUnsafeAccessors.UpdatedAt(instance) == default(DateTime));
updatedAt.SetSetter(
    FunctionCredential (FunctionCredential instance, DateTime value) =>
    {
        FunctionCredentialUnsafeAccessors.UpdatedAt(instance) = value;
        return instance;
    });
updatedAt.SetMaterializationSetter(
    FunctionCredential (FunctionCredential instance, DateTime value) =>
    {
        FunctionCredentialUnsafeAccessors.UpdatedAt(instance) = value;
        return instance;
    });
updatedAt.SetAccessors(
    DateTime (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.UpdatedAt(((FunctionCredential)(entry.Entity))),
    DateTime (IInternalEntry entry) => FunctionCredentialUnsafeAccessors.UpdatedAt(((FunctionCredential)(entry.Entity))),
    DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(updatedAt, 11),
    DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(updatedAt));
updatedAt.SetPropertyIndexes(
    index: 11,
    originalValueIndex: 11,
    shadowIndex: -1,
    relationshipIndex: -1,
    storeGenerationIndex: -1);
updatedAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
    comparer: new ValueComparer<DateTime>(
        bool (DateTime v1, DateTime v2) => v1.Equals(v2),
        int (DateTime v) => ((object)v).GetHashCode(),
        DateTime (DateTime v) => v),
    keyComparer: new ValueComparer<DateTime>(
        bool (DateTime v1, DateTime v2) => v1.Equals(v2),
        int (DateTime v) => ((object)v).GetHashCode(),
        DateTime (DateTime v) => v),
    providerValueComparer: new ValueComparer<DateTime>(
        bool (DateTime v1, DateTime v2) => v1.Equals(v2),
        int (DateTime v) => ((object)v).GetHashCode(),
        DateTime (DateTime v) => v));
updatedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var key = runtimeEntityType.AddKey(
    new[] { id });
runtimeEntityType.SetPrimaryKey(key);

var index = runtimeEntityType.AddIndex(
    new[] { functionConfigurationId });
index.AddAnnotation("Relational:Name", "IX_FunctionCredential_FunctionConfigurationId");

var index0 = runtimeEntityType.AddIndex(
    new[] { providerType });
index0.AddAnnotation("Relational:Name", "IX_FunctionCredential_ProviderType");

var index1 = runtimeEntityType.AddIndex(
    new[] { functionConfigurationId, isPrimary },
    unique: true);
index1.AddAnnotation("Relational:Filter", "\"IsPrimary\" = true AND \"FunctionConfigurationId\" IS NOT NULL");
index1.AddAnnotation("Relational:Name", "IX_FunctionCredential_OnePrimaryPerConfiguration");

var index2 = runtimeEntityType.AddIndex(
    new[] { providerType, apiKey },
    unique: true);
index2.AddAnnotation("Relational:Filter", "\"ApiKey\" IS NOT NULL AND \"FunctionConfigurationId\" IS NULL");
index2.AddAnnotation("Relational:Name", "IX_FunctionCredential_UniqueApiKeyPerProviderType");

var index3 = runtimeEntityType.AddIndex(
    new[] { providerType, isPrimary },
    unique: true);
index3.AddAnnotation("Relational:Filter", "\"IsPrimary\" = true AND \"FunctionConfigurationId\" IS NULL");
index3.AddAnnotation("Relational:Name", "IX_FunctionCredential_OnePrimaryPerProviderType");

return runtimeEntityType;
}

public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
{
    var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("FunctionConfigurationId") },
        principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
        principalEntityType,
        deleteBehavior: DeleteBehavior.Cascade);

    return runtimeForeignKey;
}

public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
{
    var id = runtimeEntityType.FindProperty("Id");
    var apiKey = runtimeEntityType.FindProperty("ApiKey");
    var baseUrl = runtimeEntityType.FindProperty("BaseUrl");
    var createdAt = runtimeEntityType.FindProperty("CreatedAt");
    var functionAccountGroup = runtimeEntityType.FindProperty("FunctionAccountGroup");
    var functionConfigurationId = runtimeEntityType.FindProperty("FunctionConfigurationId");
    var isEnabled = runtimeEntityType.FindProperty("IsEnabled");
    var isPrimary = runtimeEntityType.FindProperty("IsPrimary");
    var keyName = runtimeEntityType.FindProperty("KeyName");
    var organization = runtimeEntityType.FindProperty("Organization");
    var providerType = runtimeEntityType.FindProperty("ProviderType");
    var updatedAt = runtimeEntityType.FindProperty("UpdatedAt");
    var key = runtimeEntityType.FindKey(new[] { id });
    key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
    key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
    runtimeEntityType.SetOriginalValuesFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((FunctionCredential)(source.Entity));
            return ((ISnapshot)(new Snapshot<int, string, string, DateTime, short, int?, bool, bool, string, string, FunctionProviderType, DateTime>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<string>(apiKey) == null ? null : ((ValueComparer<string>)(((IProperty)apiKey).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(apiKey))), (source.GetCurrentValue<string>(baseUrl) == null ? null : ((ValueComparer<string>)(((IProperty)baseUrl).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(baseUrl))), ((ValueComparer<DateTime>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(createdAt)), ((ValueComparer<short>)(((IProperty)functionAccountGroup).GetValueComparer())).Snapshot(source.GetCurrentValue<short>(functionAccountGroup)), (source.GetCurrentValue<int?>(functionConfigurationId) == null ? null : ((ValueComparer<int?>)(((IProperty)functionConfigurationId).GetValueComparer())).Snapshot(source.GetCurrentValue<int?>(functionConfigurationId))), ((ValueComparer<bool>)(((IProperty)isEnabled).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isEnabled)), ((ValueComparer<bool>)(((IProperty)isPrimary).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isPrimary)), (source.GetCurrentValue<string>(keyName) == null ? null : ((ValueComparer<string>)(((IProperty)keyName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(keyName))), (source.GetCurrentValue<string>(organization) == null ? null : ((ValueComparer<string>)(((IProperty)organization).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(organization))), ((ValueComparer<FunctionProviderType>)(((IProperty)providerType).GetValueComparer())).Snapshot(source.GetCurrentValue<FunctionProviderType>(providerType)), ((ValueComparer<DateTime>)(((IProperty)updatedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(updatedAt)))));
        });
    runtimeEntityType.SetStoreGeneratedValuesFactory(
        ISnapshot () => ((ISnapshot)(new Snapshot<int, int?>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int)), (default(int? ) == null ? null : ((ValueComparer<int?>)(((IProperty)functionConfigurationId).GetValueComparer())).Snapshot(default(int? )))))));
    runtimeEntityType.SetTemporaryValuesFactory(
        ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int, int?>(default(int), default(int? )))));
    runtimeEntityType.SetShadowValuesFactory(
        ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
    runtimeEntityType.SetEmptyShadowValuesFactory(
        ISnapshot () => Snapshot.Empty);
    runtimeEntityType.SetRelationshipSnapshotFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((FunctionCredential)(source.Entity));
            return ((ISnapshot)(new Snapshot<int, int?>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<int?>(functionConfigurationId) == null ? null : ((ValueComparer<int?>)(((IProperty)functionConfigurationId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int?>(functionConfigurationId))))));
        });
    runtimeEntityType.SetCounts(new PropertyCounts(
        propertyCount: 12,
        navigationCount: 0,
        complexPropertyCount: 0,
        complexCollectionCount: 0,
        originalValueCount: 12,
        shadowCount: 0,
        relationshipCount: 2,
        storeGeneratedCount: 2));
    runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
    runtimeEntityType.AddAnnotation("Relational:Schema", null);
    runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
    runtimeEntityType.AddAnnotation("Relational:TableName", "FunctionCredentials");
    runtimeEntityType.AddAnnotation("Relational:ViewName", null);
    runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

    Customize(runtimeEntityType);
}

static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}
