// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using ConduitLLM.Functions.Entities;
using ConduitLLM.Functions.Enums;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    public static class FunctionConfigurationUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BaseUrl>k__BackingField")]
        public static extern ref string BaseUrl(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CacheTtlMinutes>k__BackingField")]
        public static extern ref int? CacheTtlMinutes(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ConfigurationName>k__BackingField")]
        public static extern ref string ConfigurationName(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DefaultExecutionMode>k__BackingField")]
        public static extern ref ExecutionMode DefaultExecutionMode(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsEnabled>k__BackingField")]
        public static extern ref bool IsEnabled(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaxRetries>k__BackingField")]
        public static extern ref int? MaxRetries(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParameterSchema>k__BackingField")]
        public static extern ref string ParameterSchema(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderSettings>k__BackingField")]
        public static extern ref string ProviderSettings(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderType>k__BackingField")]
        public static extern ref FunctionProviderType ProviderType(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Purpose>k__BackingField")]
        public static extern ref FunctionPurpose Purpose(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TimeoutSeconds>k__BackingField")]
        public static extern ref int? TimeoutSeconds(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref DateTime UpdatedAt(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CostMappings>k__BackingField")]
        public static extern ref ICollection<FunctionCostMapping> CostMappings(FunctionConfiguration @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Executions>k__BackingField")]
        public static extern ref ICollection<FunctionExecution> Executions(FunctionConfiguration @this);
    }
}
