// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using ConduitLLM.Configuration.Entities;
using ConduitLLM.Configuration.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    public static class ModelProviderTypeAssociationUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CapabilitiesLastVerifiedAt>k__BackingField")]
        public static extern ref DateTime? CapabilitiesLastVerifiedAt(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CapabilitySource>k__BackingField")]
        public static extern ref ModelCapabilitySource? CapabilitySource(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Identifier>k__BackingField")]
        public static extern ref string Identifier(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<InputModalitiesJson>k__BackingField")]
        public static extern ref string InputModalitiesJson(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsEnabled>k__BackingField")]
        public static extern ref bool IsEnabled(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsPrimary>k__BackingField")]
        public static extern ref bool IsPrimary(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaxInputTokens>k__BackingField")]
        public static extern ref int? MaxInputTokens(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaxOutputTokens>k__BackingField")]
        public static extern ref int? MaxOutputTokens(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Metadata>k__BackingField")]
        public static extern ref string Metadata(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelCostId>k__BackingField")]
        public static extern ref int? ModelCostId(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelId>k__BackingField")]
        public static extern ref int ModelId(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OperationalCapabilitiesJson>k__BackingField")]
        public static extern ref string OperationalCapabilitiesJson(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OutputModalitiesJson>k__BackingField")]
        public static extern ref string OutputModalitiesJson(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Provider>k__BackingField")]
        public static extern ref ProviderType? Provider(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderVariation>k__BackingField")]
        public static extern ref string ProviderVariation(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<QualityScore>k__BackingField")]
        public static extern ref decimal? QualityScore(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SpeedScore>k__BackingField")]
        public static extern ref decimal? SpeedScore(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Model>k__BackingField")]
        public static extern ref Model Model(ModelProviderTypeAssociation @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelCost>k__BackingField")]
        public static extern ref ModelCost ModelCost(ModelProviderTypeAssociation @this);
    }
}
