// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using ConduitLLM.Configuration.Entities;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ModelRoutePolicyEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "ConduitLLM.Configuration.Entities.ModelRoutePolicy",
                typeof(ModelRoutePolicy),
                baseEntityType,
                propertyCount: 12,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(ModelRoutePolicy).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ModelRoutePolicy).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.Id(instance),
                bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, int value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, int value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && ModelRoutePolicyUnsafeAccessors.Id(((ModelRoutePolicy)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : ModelRoutePolicyUnsafeAccessors.Id(((ModelRoutePolicy)(entry.Entity))))),
                int (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.Id(((ModelRoutePolicy)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            var affinityTtlSeconds = runtimeEntityType.AddProperty(
                "AffinityTtlSeconds",
                typeof(int),
                propertyInfo: typeof(ModelRoutePolicy).GetProperty("AffinityTtlSeconds", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ModelRoutePolicy).GetField("<AffinityTtlSeconds>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            affinityTtlSeconds.SetGetter(
                int (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.AffinityTtlSeconds(instance),
                bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.AffinityTtlSeconds(instance) == 0);
            affinityTtlSeconds.SetSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, int value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.AffinityTtlSeconds(instance) = value;
                    return instance;
                });
            affinityTtlSeconds.SetMaterializationSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, int value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.AffinityTtlSeconds(instance) = value;
                    return instance;
                });
            affinityTtlSeconds.SetAccessors(
                int (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.AffinityTtlSeconds(((ModelRoutePolicy)(entry.Entity))),
                int (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.AffinityTtlSeconds(((ModelRoutePolicy)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(affinityTtlSeconds, 1),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(affinityTtlSeconds));
            affinityTtlSeconds.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            affinityTtlSeconds.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            affinityTtlSeconds.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var cacheAffinityEnabled = runtimeEntityType.AddProperty(
                "CacheAffinityEnabled",
                typeof(bool),
                propertyInfo: typeof(ModelRoutePolicy).GetProperty("CacheAffinityEnabled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ModelRoutePolicy).GetField("<CacheAffinityEnabled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            cacheAffinityEnabled.SetGetter(
                bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.CacheAffinityEnabled(instance),
                bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.CacheAffinityEnabled(instance) == false);
            cacheAffinityEnabled.SetSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, bool value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.CacheAffinityEnabled(instance) = value;
                    return instance;
                });
            cacheAffinityEnabled.SetMaterializationSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, bool value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.CacheAffinityEnabled(instance) = value;
                    return instance;
                });
            cacheAffinityEnabled.SetAccessors(
                bool (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.CacheAffinityEnabled(((ModelRoutePolicy)(entry.Entity))),
                bool (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.CacheAffinityEnabled(((ModelRoutePolicy)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(cacheAffinityEnabled, 2),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(cacheAffinityEnabled));
            cacheAffinityEnabled.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            cacheAffinityEnabled.TypeMapping = NpgsqlBoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v));
            cacheAffinityEnabled.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var costWeight = runtimeEntityType.AddProperty(
                "CostWeight",
                typeof(decimal),
                propertyInfo: typeof(ModelRoutePolicy).GetProperty("CostWeight", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ModelRoutePolicy).GetField("<CostWeight>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            costWeight.SetGetter(
                decimal (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.CostWeight(instance),
                bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.CostWeight(instance) == 0M);
            costWeight.SetSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, decimal value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.CostWeight(instance) = value;
                    return instance;
                });
            costWeight.SetMaterializationSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, decimal value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.CostWeight(instance) = value;
                    return instance;
                });
            costWeight.SetAccessors(
                decimal (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.CostWeight(((ModelRoutePolicy)(entry.Entity))),
                decimal (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.CostWeight(((ModelRoutePolicy)(entry.Entity))),
                decimal (IInternalEntry entry) => entry.ReadOriginalValue<decimal>(costWeight, 3),
                decimal (IInternalEntry entry) => entry.GetCurrentValue<decimal>(costWeight));
            costWeight.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            costWeight.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
                comparer: new ValueComparer<decimal>(
                    bool (decimal v1, decimal v2) => v1 == v2,
                    int (decimal v) => ((object)v).GetHashCode(),
                    decimal (decimal v) => v),
                keyComparer: new ValueComparer<decimal>(
                    bool (decimal v1, decimal v2) => v1 == v2,
                    int (decimal v) => ((object)v).GetHashCode(),
                    decimal (decimal v) => v),
                providerValueComparer: new ValueComparer<decimal>(
                    bool (decimal v1, decimal v2) => v1 == v2,
                    int (decimal v) => ((object)v).GetHashCode(),
                    decimal (decimal v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "numeric(4,3)",
                    precision: 4,
                    scale: 3));
            costWeight.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            costWeight.AddAnnotation("Relational:ColumnType", "decimal(4, 3)");

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTime),
                propertyInfo: typeof(ModelRoutePolicy).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ModelRoutePolicy).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            createdAt.SetGetter(
                DateTime (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.CreatedAt(instance),
                bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.CreatedAt(instance) == default(DateTime));
            createdAt.SetSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, DateTime value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, DateTime value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                DateTime (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.CreatedAt(((ModelRoutePolicy)(entry.Entity))),
                DateTime (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.CreatedAt(((ModelRoutePolicy)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(createdAt, 4),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                keyComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                providerValueComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v));
            createdAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var isEnabled = runtimeEntityType.AddProperty(
                "IsEnabled",
                typeof(bool),
                propertyInfo: typeof(ModelRoutePolicy).GetProperty("IsEnabled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ModelRoutePolicy).GetField("<IsEnabled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isEnabled.SetGetter(
                bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.IsEnabled(instance),
                bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.IsEnabled(instance) == false);
            isEnabled.SetSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, bool value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.IsEnabled(instance) = value;
                    return instance;
                });
            isEnabled.SetMaterializationSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, bool value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.IsEnabled(instance) = value;
                    return instance;
                });
            isEnabled.SetAccessors(
                bool (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.IsEnabled(((ModelRoutePolicy)(entry.Entity))),
                bool (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.IsEnabled(((ModelRoutePolicy)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isEnabled, 5),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isEnabled));
            isEnabled.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            isEnabled.TypeMapping = NpgsqlBoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v));
            isEnabled.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var maxAffinityScorePenalty = runtimeEntityType.AddProperty(
                "MaxAffinityScorePenalty",
                typeof(decimal),
                propertyInfo: typeof(ModelRoutePolicy).GetProperty("MaxAffinityScorePenalty", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ModelRoutePolicy).GetField("<MaxAffinityScorePenalty>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            maxAffinityScorePenalty.SetGetter(
                decimal (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.MaxAffinityScorePenalty(instance),
                bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.MaxAffinityScorePenalty(instance) == 0M);
            maxAffinityScorePenalty.SetSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, decimal value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.MaxAffinityScorePenalty(instance) = value;
                    return instance;
                });
            maxAffinityScorePenalty.SetMaterializationSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, decimal value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.MaxAffinityScorePenalty(instance) = value;
                    return instance;
                });
            maxAffinityScorePenalty.SetAccessors(
                decimal (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.MaxAffinityScorePenalty(((ModelRoutePolicy)(entry.Entity))),
                decimal (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.MaxAffinityScorePenalty(((ModelRoutePolicy)(entry.Entity))),
                decimal (IInternalEntry entry) => entry.ReadOriginalValue<decimal>(maxAffinityScorePenalty, 6),
                decimal (IInternalEntry entry) => entry.GetCurrentValue<decimal>(maxAffinityScorePenalty));
            maxAffinityScorePenalty.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            maxAffinityScorePenalty.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
                comparer: new ValueComparer<decimal>(
                    bool (decimal v1, decimal v2) => v1 == v2,
                    int (decimal v) => ((object)v).GetHashCode(),
                    decimal (decimal v) => v),
                keyComparer: new ValueComparer<decimal>(
                    bool (decimal v1, decimal v2) => v1 == v2,
                    int (decimal v) => ((object)v).GetHashCode(),
                    decimal (decimal v) => v),
                providerValueComparer: new ValueComparer<decimal>(
                    bool (decimal v1, decimal v2) => v1 == v2,
                    int (decimal v) => ((object)v).GetHashCode(),
                    decimal (decimal v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "numeric(4,3)",
                    precision: 4,
                    scale: 3));
            maxAffinityScorePenalty.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            maxAffinityScorePenalty.AddAnnotation("Relational:ColumnType", "decimal(4, 3)");

            var modelAlias = runtimeEntityType.AddProperty(
                "ModelAlias",
                typeof(string),
                propertyInfo: typeof(ModelRoutePolicy).GetProperty("ModelAlias", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ModelRoutePolicy).GetField("<ModelAlias>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            modelAlias.SetGetter(
                string (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.ModelAlias(instance),
                bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.ModelAlias(instance) == null);
            modelAlias.SetSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, string value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.ModelAlias(instance) = value;
                    return instance;
                });
            modelAlias.SetMaterializationSetter(
                ModelRoutePolicy (ModelRoutePolicy instance, string value) =>
                {
                    ModelRoutePolicyUnsafeAccessors.ModelAlias(instance) = value;
                    return instance;
                });
            modelAlias.SetAccessors(
                string (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.ModelAlias(((ModelRoutePolicy)(entry.Entity))),
                string (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.ModelAlias(((ModelRoutePolicy)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(modelAlias, 7),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(modelAlias));
            modelAlias.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            modelAlias.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(100)",
                    size: 100));
            modelAlias.TypeMapping = ((NpgsqlStringTypeMapping)modelAlias.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        modelAlias.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(modelAlias));
        modelAlias.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var qualityWeight = runtimeEntityType.AddProperty(
            "QualityWeight",
            typeof(decimal),
            propertyInfo: typeof(ModelRoutePolicy).GetProperty("QualityWeight", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ModelRoutePolicy).GetField("<QualityWeight>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0m);
        qualityWeight.SetGetter(
            decimal (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.QualityWeight(instance),
            bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.QualityWeight(instance) == 0M);
        qualityWeight.SetSetter(
            ModelRoutePolicy (ModelRoutePolicy instance, decimal value) =>
            {
                ModelRoutePolicyUnsafeAccessors.QualityWeight(instance) = value;
                return instance;
            });
        qualityWeight.SetMaterializationSetter(
            ModelRoutePolicy (ModelRoutePolicy instance, decimal value) =>
            {
                ModelRoutePolicyUnsafeAccessors.QualityWeight(instance) = value;
                return instance;
            });
        qualityWeight.SetAccessors(
            decimal (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.QualityWeight(((ModelRoutePolicy)(entry.Entity))),
            decimal (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.QualityWeight(((ModelRoutePolicy)(entry.Entity))),
            decimal (IInternalEntry entry) => entry.ReadOriginalValue<decimal>(qualityWeight, 8),
            decimal (IInternalEntry entry) => entry.GetCurrentValue<decimal>(qualityWeight));
        qualityWeight.SetPropertyIndexes(
            index: 8,
            originalValueIndex: 8,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        qualityWeight.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
            comparer: new ValueComparer<decimal>(
                bool (decimal v1, decimal v2) => v1 == v2,
                int (decimal v) => ((object)v).GetHashCode(),
                decimal (decimal v) => v),
            keyComparer: new ValueComparer<decimal>(
                bool (decimal v1, decimal v2) => v1 == v2,
                int (decimal v) => ((object)v).GetHashCode(),
                decimal (decimal v) => v),
            providerValueComparer: new ValueComparer<decimal>(
                bool (decimal v1, decimal v2) => v1 == v2,
                int (decimal v) => ((object)v).GetHashCode(),
                decimal (decimal v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "numeric(4,3)",
                precision: 4,
                scale: 3));
        qualityWeight.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        qualityWeight.AddAnnotation("Relational:ColumnType", "decimal(4, 3)");

        var speedWeight = runtimeEntityType.AddProperty(
            "SpeedWeight",
            typeof(decimal),
            propertyInfo: typeof(ModelRoutePolicy).GetProperty("SpeedWeight", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ModelRoutePolicy).GetField("<SpeedWeight>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0m);
        speedWeight.SetGetter(
            decimal (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.SpeedWeight(instance),
            bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.SpeedWeight(instance) == 0M);
        speedWeight.SetSetter(
            ModelRoutePolicy (ModelRoutePolicy instance, decimal value) =>
            {
                ModelRoutePolicyUnsafeAccessors.SpeedWeight(instance) = value;
                return instance;
            });
        speedWeight.SetMaterializationSetter(
            ModelRoutePolicy (ModelRoutePolicy instance, decimal value) =>
            {
                ModelRoutePolicyUnsafeAccessors.SpeedWeight(instance) = value;
                return instance;
            });
        speedWeight.SetAccessors(
            decimal (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.SpeedWeight(((ModelRoutePolicy)(entry.Entity))),
            decimal (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.SpeedWeight(((ModelRoutePolicy)(entry.Entity))),
            decimal (IInternalEntry entry) => entry.ReadOriginalValue<decimal>(speedWeight, 9),
            decimal (IInternalEntry entry) => entry.GetCurrentValue<decimal>(speedWeight));
        speedWeight.SetPropertyIndexes(
            index: 9,
            originalValueIndex: 9,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        speedWeight.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
            comparer: new ValueComparer<decimal>(
                bool (decimal v1, decimal v2) => v1 == v2,
                int (decimal v) => ((object)v).GetHashCode(),
                decimal (decimal v) => v),
            keyComparer: new ValueComparer<decimal>(
                bool (decimal v1, decimal v2) => v1 == v2,
                int (decimal v) => ((object)v).GetHashCode(),
                decimal (decimal v) => v),
            providerValueComparer: new ValueComparer<decimal>(
                bool (decimal v1, decimal v2) => v1 == v2,
                int (decimal v) => ((object)v).GetHashCode(),
                decimal (decimal v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "numeric(4,3)",
                precision: 4,
                scale: 3));
        speedWeight.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
        speedWeight.AddAnnotation("Relational:ColumnType", "decimal(4, 3)");

        var strategy = runtimeEntityType.AddProperty(
            "Strategy",
            typeof(string),
            propertyInfo: typeof(ModelRoutePolicy).GetProperty("Strategy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ModelRoutePolicy).GetField("<Strategy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            maxLength: 30);
        strategy.SetGetter(
            string (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.Strategy(instance),
            bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.Strategy(instance) == null);
        strategy.SetSetter(
            ModelRoutePolicy (ModelRoutePolicy instance, string value) =>
            {
                ModelRoutePolicyUnsafeAccessors.Strategy(instance) = value;
                return instance;
            });
        strategy.SetMaterializationSetter(
            ModelRoutePolicy (ModelRoutePolicy instance, string value) =>
            {
                ModelRoutePolicyUnsafeAccessors.Strategy(instance) = value;
                return instance;
            });
        strategy.SetAccessors(
            string (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.Strategy(((ModelRoutePolicy)(entry.Entity))),
            string (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.Strategy(((ModelRoutePolicy)(entry.Entity))),
            string (IInternalEntry entry) => entry.ReadOriginalValue<string>(strategy, 10),
            string (IInternalEntry entry) => entry.GetCurrentValue<string>(strategy));
        strategy.SetPropertyIndexes(
            index: 10,
            originalValueIndex: 10,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        strategy.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
            comparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            keyComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            providerValueComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "character varying(30)",
                size: 30));
        strategy.TypeMapping = ((NpgsqlStringTypeMapping)strategy.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
    strategy.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var updatedAt = runtimeEntityType.AddProperty(
        "UpdatedAt",
        typeof(DateTime),
        propertyInfo: typeof(ModelRoutePolicy).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(ModelRoutePolicy).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
    updatedAt.SetGetter(
        DateTime (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.UpdatedAt(instance),
        bool (ModelRoutePolicy instance) => ModelRoutePolicyUnsafeAccessors.UpdatedAt(instance) == default(DateTime));
    updatedAt.SetSetter(
        ModelRoutePolicy (ModelRoutePolicy instance, DateTime value) =>
        {
            ModelRoutePolicyUnsafeAccessors.UpdatedAt(instance) = value;
            return instance;
        });
    updatedAt.SetMaterializationSetter(
        ModelRoutePolicy (ModelRoutePolicy instance, DateTime value) =>
        {
            ModelRoutePolicyUnsafeAccessors.UpdatedAt(instance) = value;
            return instance;
        });
    updatedAt.SetAccessors(
        DateTime (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.UpdatedAt(((ModelRoutePolicy)(entry.Entity))),
        DateTime (IInternalEntry entry) => ModelRoutePolicyUnsafeAccessors.UpdatedAt(((ModelRoutePolicy)(entry.Entity))),
        DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(updatedAt, 11),
        DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(updatedAt));
    updatedAt.SetPropertyIndexes(
        index: 11,
        originalValueIndex: 11,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    updatedAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
        comparer: new ValueComparer<DateTime>(
            bool (DateTime v1, DateTime v2) => v1.Equals(v2),
            int (DateTime v) => ((object)v).GetHashCode(),
            DateTime (DateTime v) => v),
        keyComparer: new ValueComparer<DateTime>(
            bool (DateTime v1, DateTime v2) => v1.Equals(v2),
            int (DateTime v) => ((object)v).GetHashCode(),
            DateTime (DateTime v) => v),
        providerValueComparer: new ValueComparer<DateTime>(
            bool (DateTime v1, DateTime v2) => v1.Equals(v2),
            int (DateTime v) => ((object)v).GetHashCode(),
            DateTime (DateTime v) => v));
    updatedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var key = runtimeEntityType.AddKey(
        new[] { id });
    runtimeEntityType.SetPrimaryKey(key);

    var index = runtimeEntityType.AddIndex(
        new[] { modelAlias },
        unique: true);

    return runtimeEntityType;
}

public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
{
    var id = runtimeEntityType.FindProperty("Id");
    var affinityTtlSeconds = runtimeEntityType.FindProperty("AffinityTtlSeconds");
    var cacheAffinityEnabled = runtimeEntityType.FindProperty("CacheAffinityEnabled");
    var costWeight = runtimeEntityType.FindProperty("CostWeight");
    var createdAt = runtimeEntityType.FindProperty("CreatedAt");
    var isEnabled = runtimeEntityType.FindProperty("IsEnabled");
    var maxAffinityScorePenalty = runtimeEntityType.FindProperty("MaxAffinityScorePenalty");
    var modelAlias = runtimeEntityType.FindProperty("ModelAlias");
    var qualityWeight = runtimeEntityType.FindProperty("QualityWeight");
    var speedWeight = runtimeEntityType.FindProperty("SpeedWeight");
    var strategy = runtimeEntityType.FindProperty("Strategy");
    var updatedAt = runtimeEntityType.FindProperty("UpdatedAt");
    var key = runtimeEntityType.FindKey(new[] { id });
    key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
    key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
    runtimeEntityType.SetOriginalValuesFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((ModelRoutePolicy)(source.Entity));
            return ((ISnapshot)(new Snapshot<int, int, bool, decimal, DateTime, bool, decimal, string, decimal, decimal, string, DateTime>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<int>)(((IProperty)affinityTtlSeconds).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(affinityTtlSeconds)), ((ValueComparer<bool>)(((IProperty)cacheAffinityEnabled).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(cacheAffinityEnabled)), ((ValueComparer<decimal>)(((IProperty)costWeight).GetValueComparer())).Snapshot(source.GetCurrentValue<decimal>(costWeight)), ((ValueComparer<DateTime>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(createdAt)), ((ValueComparer<bool>)(((IProperty)isEnabled).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isEnabled)), ((ValueComparer<decimal>)(((IProperty)maxAffinityScorePenalty).GetValueComparer())).Snapshot(source.GetCurrentValue<decimal>(maxAffinityScorePenalty)), (source.GetCurrentValue<string>(modelAlias) == null ? null : ((ValueComparer<string>)(((IProperty)modelAlias).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(modelAlias))), ((ValueComparer<decimal>)(((IProperty)qualityWeight).GetValueComparer())).Snapshot(source.GetCurrentValue<decimal>(qualityWeight)), ((ValueComparer<decimal>)(((IProperty)speedWeight).GetValueComparer())).Snapshot(source.GetCurrentValue<decimal>(speedWeight)), (source.GetCurrentValue<string>(strategy) == null ? null : ((ValueComparer<string>)(((IProperty)strategy).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(strategy))), ((ValueComparer<DateTime>)(((IProperty)updatedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(updatedAt)))));
        });
    runtimeEntityType.SetStoreGeneratedValuesFactory(
        ISnapshot () => ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
    runtimeEntityType.SetTemporaryValuesFactory(
        ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int>(default(int)))));
    runtimeEntityType.SetShadowValuesFactory(
        ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
    runtimeEntityType.SetEmptyShadowValuesFactory(
        ISnapshot () => Snapshot.Empty);
    runtimeEntityType.SetRelationshipSnapshotFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((ModelRoutePolicy)(source.Entity));
            return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
        });
    runtimeEntityType.SetCounts(new PropertyCounts(
        propertyCount: 12,
        navigationCount: 0,
        complexPropertyCount: 0,
        complexCollectionCount: 0,
        originalValueCount: 12,
        shadowCount: 0,
        relationshipCount: 1,
        storeGeneratedCount: 1));
    runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
    runtimeEntityType.AddAnnotation("Relational:Schema", null);
    runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
    runtimeEntityType.AddAnnotation("Relational:TableName", "ModelRoutePolicies");
    runtimeEntityType.AddAnnotation("Relational:ViewName", null);
    runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

    Customize(runtimeEntityType);
}

static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}
