// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using ConduitLLM.Configuration.Entities;
using ConduitLLM.Configuration.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    public static class ModelUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CapabilitiesLastVerifiedAt>k__BackingField")]
        public static extern ref DateTime? CapabilitiesLastVerifiedAt(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CapabilitySource>k__BackingField")]
        public static extern ref ModelCapabilitySource CapabilitySource(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<InputModalitiesJson>k__BackingField")]
        public static extern ref string InputModalitiesJson(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
        public static extern ref bool IsActive(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaxInputTokens>k__BackingField")]
        public static extern ref int? MaxInputTokens(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaxOutputTokens>k__BackingField")]
        public static extern ref int? MaxOutputTokens(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelCardUrl>k__BackingField")]
        public static extern ref string ModelCardUrl(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelParameters>k__BackingField")]
        public static extern ref string ModelParameters(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelSeriesId>k__BackingField")]
        public static extern ref int ModelSeriesId(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OutputModalitiesJson>k__BackingField")]
        public static extern ref string OutputModalitiesJson(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SupportsChat>k__BackingField")]
        public static extern ref bool SupportsChat(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SupportsEmbeddings>k__BackingField")]
        public static extern ref bool SupportsEmbeddings(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SupportsFunctionCalling>k__BackingField")]
        public static extern ref bool SupportsFunctionCalling(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SupportsImageGeneration>k__BackingField")]
        public static extern ref bool SupportsImageGeneration(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SupportsRerank>k__BackingField")]
        public static extern ref bool SupportsRerank(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SupportsSpeechToText>k__BackingField")]
        public static extern ref bool SupportsSpeechToText(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SupportsStreaming>k__BackingField")]
        public static extern ref bool SupportsStreaming(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SupportsTextToSpeech>k__BackingField")]
        public static extern ref bool SupportsTextToSpeech(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SupportsVideoGeneration>k__BackingField")]
        public static extern ref bool SupportsVideoGeneration(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SupportsVision>k__BackingField")]
        public static extern ref bool SupportsVision(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TokenizerType>k__BackingField")]
        public static extern ref TokenizerType TokenizerType(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref DateTime UpdatedAt(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Version>k__BackingField")]
        public static extern ref string Version(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Identifiers>k__BackingField")]
        public static extern ref ICollection<ModelProviderTypeAssociation> Identifiers(Model @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Series>k__BackingField")]
        public static extern ref ModelSeries Series(Model @this);
    }
}
