// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using ConduitLLM.Configuration.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    public static class ModelProviderMappingUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(ModelProviderMapping @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(ModelProviderMapping @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsEnabled>k__BackingField")]
        public static extern ref bool IsEnabled(ModelProviderMapping @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelAlias>k__BackingField")]
        public static extern ref string ModelAlias(ModelProviderMapping @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelProviderTypeAssociationId>k__BackingField")]
        public static extern ref int ModelProviderTypeAssociationId(ModelProviderMapping @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderId>k__BackingField")]
        public static extern ref int ProviderId(ModelProviderMapping @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderModelId>k__BackingField")]
        public static extern ref string ProviderModelId(ModelProviderMapping @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderOptions>k__BackingField")]
        public static extern ref string ProviderOptions(ModelProviderMapping @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RoutingPriority>k__BackingField")]
        public static extern ref int RoutingPriority(ModelProviderMapping @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RoutingWeight>k__BackingField")]
        public static extern ref decimal RoutingWeight(ModelProviderMapping @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref DateTime UpdatedAt(ModelProviderMapping @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelProviderTypeAssociation>k__BackingField")]
        public static extern ref ModelProviderTypeAssociation ModelProviderTypeAssociation(ModelProviderMapping @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Provider>k__BackingField")]
        public static extern ref Provider Provider(ModelProviderMapping @this);
    }
}
