// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using ConduitLLM.Configuration.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    public static class NotificationUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(Notification @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(Notification @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsRead>k__BackingField")]
        public static extern ref bool IsRead(Notification @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Message>k__BackingField")]
        public static extern ref string Message(Notification @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderId>k__BackingField")]
        public static extern ref int? ProviderId(Notification @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderKeyCredentialId>k__BackingField")]
        public static extern ref int? ProviderKeyCredentialId(Notification @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Severity>k__BackingField")]
        public static extern ref NotificationSeverity Severity(Notification @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
        public static extern ref NotificationType Type(Notification @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<VirtualKeyId>k__BackingField")]
        public static extern ref int? VirtualKeyId(Notification @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Provider>k__BackingField")]
        public static extern ref Provider Provider(Notification @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderKeyCredential>k__BackingField")]
        public static extern ref ProviderKeyCredential ProviderKeyCredential(Notification @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<VirtualKey>k__BackingField")]
        public static extern ref VirtualKey VirtualKey(Notification @this);
    }
}
