// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using ConduitLLM.Configuration.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    public static class ProviderMetadataSyncRunUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(ProviderMetadataSyncRun @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompletedAt>k__BackingField")]
        public static extern ref DateTime? CompletedAt(ProviderMetadataSyncRun @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ErrorMessage>k__BackingField")]
        public static extern ref string ErrorMessage(ProviderMetadataSyncRun @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ItemsAutoResolved>k__BackingField")]
        public static extern ref int ItemsAutoResolved(ProviderMetadataSyncRun @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ItemsCreated>k__BackingField")]
        public static extern ref int ItemsCreated(ProviderMetadataSyncRun @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ItemsUpdated>k__BackingField")]
        public static extern ref int ItemsUpdated(ProviderMetadataSyncRun @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MappingsChecked>k__BackingField")]
        public static extern ref int MappingsChecked(ProviderMetadataSyncRun @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelsFetched>k__BackingField")]
        public static extern ref int ModelsFetched(ProviderMetadataSyncRun @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderType>k__BackingField")]
        public static extern ref ProviderType ProviderType(ProviderMetadataSyncRun @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StartedAt>k__BackingField")]
        public static extern ref DateTime StartedAt(ProviderMetadataSyncRun @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
        public static extern ref string Status(ProviderMetadataSyncRun @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TriggeredBy>k__BackingField")]
        public static extern ref string TriggeredBy(ProviderMetadataSyncRun @this);
    }
}
