// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using ConduitLLM.Configuration.Entities;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ProviderMetadataSyncRunEntityType
    {
        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(
            "AOT",
            "IL3050",
            Justification = "EF Core 10 generates closed enum/array mapping setup through APIs annotated for arbitrary runtime types. Every concrete type is statically named and rooted by this compiled model. Owner: database/runtime maintainers; upstream: dotnet/efcore#29754; remove when the generator emits warning-free mappings.")]
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "ConduitLLM.Configuration.Entities.ProviderMetadataSyncRun",
                typeof(ProviderMetadataSyncRun),
                baseEntityType,
                propertyCount: 12,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(ProviderMetadataSyncRun).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProviderMetadataSyncRun).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.Id(instance),
                bool (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, int value) =>
                {
                    ProviderMetadataSyncRunUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, int value) =>
                {
                    ProviderMetadataSyncRunUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && ProviderMetadataSyncRunUnsafeAccessors.Id(((ProviderMetadataSyncRun)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : ProviderMetadataSyncRunUnsafeAccessors.Id(((ProviderMetadataSyncRun)(entry.Entity))))),
                int (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.Id(((ProviderMetadataSyncRun)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "integer"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            var completedAt = runtimeEntityType.AddProperty(
                "CompletedAt",
                typeof(DateTime?),
                propertyInfo: typeof(ProviderMetadataSyncRun).GetProperty("CompletedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProviderMetadataSyncRun).GetField("<CompletedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            completedAt.SetGetter(
                DateTime? (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.CompletedAt(instance),
                bool (ProviderMetadataSyncRun instance) => !(ProviderMetadataSyncRunUnsafeAccessors.CompletedAt(instance).HasValue));
            completedAt.SetSetter(
                ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, DateTime? value) =>
                {
                    ProviderMetadataSyncRunUnsafeAccessors.CompletedAt(instance) = value;
                    return instance;
                });
            completedAt.SetMaterializationSetter(
                ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, DateTime? value) =>
                {
                    ProviderMetadataSyncRunUnsafeAccessors.CompletedAt(instance) = value;
                    return instance;
                });
            completedAt.SetAccessors(
                DateTime? (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.CompletedAt(((ProviderMetadataSyncRun)(entry.Entity))),
                DateTime? (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.CompletedAt(((ProviderMetadataSyncRun)(entry.Entity))),
                DateTime? (IInternalEntry entry) => entry.ReadOriginalValue<DateTime?>(completedAt, 1),
                DateTime? (IInternalEntry entry) => entry.GetCurrentValue<DateTime?>(completedAt));
            completedAt.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            completedAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                keyComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                providerValueComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v));
            completedAt.SetComparer(new NullableValueComparer<DateTime>(completedAt.TypeMapping.Comparer));
            completedAt.SetKeyComparer(new NullableValueComparer<DateTime>(completedAt.TypeMapping.KeyComparer));
            completedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var errorMessage = runtimeEntityType.AddProperty(
                "ErrorMessage",
                typeof(string),
                propertyInfo: typeof(ProviderMetadataSyncRun).GetProperty("ErrorMessage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ProviderMetadataSyncRun).GetField("<ErrorMessage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            errorMessage.SetGetter(
                string (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.ErrorMessage(instance),
                bool (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.ErrorMessage(instance) == null);
            errorMessage.SetSetter(
                ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, string value) =>
                {
                    ProviderMetadataSyncRunUnsafeAccessors.ErrorMessage(instance) = value;
                    return instance;
                });
            errorMessage.SetMaterializationSetter(
                ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, string value) =>
                {
                    ProviderMetadataSyncRunUnsafeAccessors.ErrorMessage(instance) = value;
                    return instance;
                });
            errorMessage.SetAccessors(
                string (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.ErrorMessage(((ProviderMetadataSyncRun)(entry.Entity))),
                string (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.ErrorMessage(((ProviderMetadataSyncRun)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(errorMessage, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(errorMessage));
            errorMessage.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            errorMessage.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(2000)",
                    size: 2000));
            errorMessage.TypeMapping = ((NpgsqlStringTypeMapping)errorMessage.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        errorMessage.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var itemsAutoResolved = runtimeEntityType.AddProperty(
            "ItemsAutoResolved",
            typeof(int),
            propertyInfo: typeof(ProviderMetadataSyncRun).GetProperty("ItemsAutoResolved", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ProviderMetadataSyncRun).GetField("<ItemsAutoResolved>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0);
        itemsAutoResolved.SetGetter(
            int (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.ItemsAutoResolved(instance),
            bool (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.ItemsAutoResolved(instance) == 0);
        itemsAutoResolved.SetSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, int value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.ItemsAutoResolved(instance) = value;
                return instance;
            });
        itemsAutoResolved.SetMaterializationSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, int value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.ItemsAutoResolved(instance) = value;
                return instance;
            });
        itemsAutoResolved.SetAccessors(
            int (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.ItemsAutoResolved(((ProviderMetadataSyncRun)(entry.Entity))),
            int (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.ItemsAutoResolved(((ProviderMetadataSyncRun)(entry.Entity))),
            int (IInternalEntry entry) => entry.ReadOriginalValue<int>(itemsAutoResolved, 3),
            int (IInternalEntry entry) => entry.GetCurrentValue<int>(itemsAutoResolved));
        itemsAutoResolved.SetPropertyIndexes(
            index: 3,
            originalValueIndex: 3,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        itemsAutoResolved.TypeMapping = IntTypeMapping.Default.Clone(
            comparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            keyComparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            providerValueComparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "integer"));
        itemsAutoResolved.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var itemsCreated = runtimeEntityType.AddProperty(
            "ItemsCreated",
            typeof(int),
            propertyInfo: typeof(ProviderMetadataSyncRun).GetProperty("ItemsCreated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ProviderMetadataSyncRun).GetField("<ItemsCreated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0);
        itemsCreated.SetGetter(
            int (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.ItemsCreated(instance),
            bool (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.ItemsCreated(instance) == 0);
        itemsCreated.SetSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, int value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.ItemsCreated(instance) = value;
                return instance;
            });
        itemsCreated.SetMaterializationSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, int value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.ItemsCreated(instance) = value;
                return instance;
            });
        itemsCreated.SetAccessors(
            int (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.ItemsCreated(((ProviderMetadataSyncRun)(entry.Entity))),
            int (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.ItemsCreated(((ProviderMetadataSyncRun)(entry.Entity))),
            int (IInternalEntry entry) => entry.ReadOriginalValue<int>(itemsCreated, 4),
            int (IInternalEntry entry) => entry.GetCurrentValue<int>(itemsCreated));
        itemsCreated.SetPropertyIndexes(
            index: 4,
            originalValueIndex: 4,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        itemsCreated.TypeMapping = IntTypeMapping.Default.Clone(
            comparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            keyComparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            providerValueComparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "integer"));
        itemsCreated.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var itemsUpdated = runtimeEntityType.AddProperty(
            "ItemsUpdated",
            typeof(int),
            propertyInfo: typeof(ProviderMetadataSyncRun).GetProperty("ItemsUpdated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ProviderMetadataSyncRun).GetField("<ItemsUpdated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0);
        itemsUpdated.SetGetter(
            int (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.ItemsUpdated(instance),
            bool (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.ItemsUpdated(instance) == 0);
        itemsUpdated.SetSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, int value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.ItemsUpdated(instance) = value;
                return instance;
            });
        itemsUpdated.SetMaterializationSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, int value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.ItemsUpdated(instance) = value;
                return instance;
            });
        itemsUpdated.SetAccessors(
            int (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.ItemsUpdated(((ProviderMetadataSyncRun)(entry.Entity))),
            int (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.ItemsUpdated(((ProviderMetadataSyncRun)(entry.Entity))),
            int (IInternalEntry entry) => entry.ReadOriginalValue<int>(itemsUpdated, 5),
            int (IInternalEntry entry) => entry.GetCurrentValue<int>(itemsUpdated));
        itemsUpdated.SetPropertyIndexes(
            index: 5,
            originalValueIndex: 5,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        itemsUpdated.TypeMapping = IntTypeMapping.Default.Clone(
            comparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            keyComparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            providerValueComparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "integer"));
        itemsUpdated.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var mappingsChecked = runtimeEntityType.AddProperty(
            "MappingsChecked",
            typeof(int),
            propertyInfo: typeof(ProviderMetadataSyncRun).GetProperty("MappingsChecked", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ProviderMetadataSyncRun).GetField("<MappingsChecked>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0);
        mappingsChecked.SetGetter(
            int (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.MappingsChecked(instance),
            bool (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.MappingsChecked(instance) == 0);
        mappingsChecked.SetSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, int value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.MappingsChecked(instance) = value;
                return instance;
            });
        mappingsChecked.SetMaterializationSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, int value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.MappingsChecked(instance) = value;
                return instance;
            });
        mappingsChecked.SetAccessors(
            int (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.MappingsChecked(((ProviderMetadataSyncRun)(entry.Entity))),
            int (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.MappingsChecked(((ProviderMetadataSyncRun)(entry.Entity))),
            int (IInternalEntry entry) => entry.ReadOriginalValue<int>(mappingsChecked, 6),
            int (IInternalEntry entry) => entry.GetCurrentValue<int>(mappingsChecked));
        mappingsChecked.SetPropertyIndexes(
            index: 6,
            originalValueIndex: 6,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        mappingsChecked.TypeMapping = IntTypeMapping.Default.Clone(
            comparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            keyComparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            providerValueComparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "integer"));
        mappingsChecked.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var modelsFetched = runtimeEntityType.AddProperty(
            "ModelsFetched",
            typeof(int),
            propertyInfo: typeof(ProviderMetadataSyncRun).GetProperty("ModelsFetched", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ProviderMetadataSyncRun).GetField("<ModelsFetched>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0);
        modelsFetched.SetGetter(
            int (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.ModelsFetched(instance),
            bool (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.ModelsFetched(instance) == 0);
        modelsFetched.SetSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, int value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.ModelsFetched(instance) = value;
                return instance;
            });
        modelsFetched.SetMaterializationSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, int value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.ModelsFetched(instance) = value;
                return instance;
            });
        modelsFetched.SetAccessors(
            int (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.ModelsFetched(((ProviderMetadataSyncRun)(entry.Entity))),
            int (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.ModelsFetched(((ProviderMetadataSyncRun)(entry.Entity))),
            int (IInternalEntry entry) => entry.ReadOriginalValue<int>(modelsFetched, 7),
            int (IInternalEntry entry) => entry.GetCurrentValue<int>(modelsFetched));
        modelsFetched.SetPropertyIndexes(
            index: 7,
            originalValueIndex: 7,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        modelsFetched.TypeMapping = IntTypeMapping.Default.Clone(
            comparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            keyComparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            providerValueComparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "integer"));
        modelsFetched.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var providerType = runtimeEntityType.AddProperty(
            "ProviderType",
            typeof(ProviderType),
            propertyInfo: typeof(ProviderMetadataSyncRun).GetProperty("ProviderType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ProviderMetadataSyncRun).GetField("<ProviderType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
        providerType.SetGetter(
            ProviderType (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.ProviderType(instance),
            bool (ProviderMetadataSyncRun instance) => object.Equals(((object)(ProviderMetadataSyncRunUnsafeAccessors.ProviderType(instance))), ((object)(ProviderType.Unknown))));
        providerType.SetSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, ProviderType value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.ProviderType(instance) = value;
                return instance;
            });
        providerType.SetMaterializationSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, ProviderType value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.ProviderType(instance) = value;
                return instance;
            });
        providerType.SetAccessors(
            ProviderType (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.ProviderType(((ProviderMetadataSyncRun)(entry.Entity))),
            ProviderType (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.ProviderType(((ProviderMetadataSyncRun)(entry.Entity))),
            ProviderType (IInternalEntry entry) => entry.ReadOriginalValue<ProviderType>(providerType, 8),
            ProviderType (IInternalEntry entry) => entry.GetCurrentValue<ProviderType>(providerType));
        providerType.SetPropertyIndexes(
            index: 8,
            originalValueIndex: 8,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        providerType.TypeMapping = IntTypeMapping.Default.Clone(
            comparer: new ValueComparer<ProviderType>(
                bool (ProviderType v1, ProviderType v2) => object.Equals(((object)v1), ((object)v2)),
                int (ProviderType v) => ((object)v).GetHashCode(),
                ProviderType (ProviderType v) => v),
            keyComparer: new ValueComparer<ProviderType>(
                bool (ProviderType v1, ProviderType v2) => object.Equals(((object)v1), ((object)v2)),
                int (ProviderType v) => ((object)v).GetHashCode(),
                ProviderType (ProviderType v) => v),
            providerValueComparer: new ValueComparer<int>(
                bool (int v1, int v2) => v1 == v2,
                int (int v) => v,
                int (int v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "integer"),
            converter: new ValueConverter<ProviderType, int>(
                int (ProviderType value) => ((int)value),
                ProviderType (int value) => ((ProviderType)value)),
            jsonValueReaderWriter: new JsonConvertedValueReaderWriter<ProviderType, int>(
                JsonInt32ReaderWriter.Instance,
                new ValueConverter<ProviderType, int>(
                    int (ProviderType value) => ((int)value),
                    ProviderType (int value) => ((ProviderType)value))));
        providerType.SetSentinelFromProviderValue(0);
        providerType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var startedAt = runtimeEntityType.AddProperty(
            "StartedAt",
            typeof(DateTime),
            propertyInfo: typeof(ProviderMetadataSyncRun).GetProperty("StartedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ProviderMetadataSyncRun).GetField("<StartedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
        startedAt.SetGetter(
            DateTime (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.StartedAt(instance),
            bool (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.StartedAt(instance) == default(DateTime));
        startedAt.SetSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, DateTime value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.StartedAt(instance) = value;
                return instance;
            });
        startedAt.SetMaterializationSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, DateTime value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.StartedAt(instance) = value;
                return instance;
            });
        startedAt.SetAccessors(
            DateTime (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.StartedAt(((ProviderMetadataSyncRun)(entry.Entity))),
            DateTime (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.StartedAt(((ProviderMetadataSyncRun)(entry.Entity))),
            DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(startedAt, 9),
            DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(startedAt));
        startedAt.SetPropertyIndexes(
            index: 9,
            originalValueIndex: 9,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        startedAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
            comparer: new ValueComparer<DateTime>(
                bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                int (DateTime v) => ((object)v).GetHashCode(),
                DateTime (DateTime v) => v),
            keyComparer: new ValueComparer<DateTime>(
                bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                int (DateTime v) => ((object)v).GetHashCode(),
                DateTime (DateTime v) => v),
            providerValueComparer: new ValueComparer<DateTime>(
                bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                int (DateTime v) => ((object)v).GetHashCode(),
                DateTime (DateTime v) => v));
        startedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var status = runtimeEntityType.AddProperty(
            "Status",
            typeof(string),
            propertyInfo: typeof(ProviderMetadataSyncRun).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(ProviderMetadataSyncRun).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            maxLength: 20);
        status.SetGetter(
            string (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.Status(instance),
            bool (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.Status(instance) == null);
        status.SetSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, string value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.Status(instance) = value;
                return instance;
            });
        status.SetMaterializationSetter(
            ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, string value) =>
            {
                ProviderMetadataSyncRunUnsafeAccessors.Status(instance) = value;
                return instance;
            });
        status.SetAccessors(
            string (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.Status(((ProviderMetadataSyncRun)(entry.Entity))),
            string (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.Status(((ProviderMetadataSyncRun)(entry.Entity))),
            string (IInternalEntry entry) => entry.ReadOriginalValue<string>(status, 10),
            string (IInternalEntry entry) => entry.GetCurrentValue<string>(status));
        status.SetPropertyIndexes(
            index: 10,
            originalValueIndex: 10,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        status.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
            comparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            keyComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            providerValueComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "character varying(20)",
                size: 20));
        status.TypeMapping = ((NpgsqlStringTypeMapping)status.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
    status.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var triggeredBy = runtimeEntityType.AddProperty(
        "TriggeredBy",
        typeof(string),
        propertyInfo: typeof(ProviderMetadataSyncRun).GetProperty("TriggeredBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(ProviderMetadataSyncRun).GetField("<TriggeredBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        maxLength: 100);
    triggeredBy.SetGetter(
        string (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.TriggeredBy(instance),
        bool (ProviderMetadataSyncRun instance) => ProviderMetadataSyncRunUnsafeAccessors.TriggeredBy(instance) == null);
    triggeredBy.SetSetter(
        ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, string value) =>
        {
            ProviderMetadataSyncRunUnsafeAccessors.TriggeredBy(instance) = value;
            return instance;
        });
    triggeredBy.SetMaterializationSetter(
        ProviderMetadataSyncRun (ProviderMetadataSyncRun instance, string value) =>
        {
            ProviderMetadataSyncRunUnsafeAccessors.TriggeredBy(instance) = value;
            return instance;
        });
    triggeredBy.SetAccessors(
        string (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.TriggeredBy(((ProviderMetadataSyncRun)(entry.Entity))),
        string (IInternalEntry entry) => ProviderMetadataSyncRunUnsafeAccessors.TriggeredBy(((ProviderMetadataSyncRun)(entry.Entity))),
        string (IInternalEntry entry) => entry.ReadOriginalValue<string>(triggeredBy, 11),
        string (IInternalEntry entry) => entry.GetCurrentValue<string>(triggeredBy));
    triggeredBy.SetPropertyIndexes(
        index: 11,
        originalValueIndex: 11,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    triggeredBy.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
        comparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        keyComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        providerValueComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        mappingInfo: new RelationalTypeMappingInfo(
            storeTypeName: "character varying(100)",
            size: 100));
    triggeredBy.TypeMapping = ((NpgsqlStringTypeMapping)triggeredBy.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
triggeredBy.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var key = runtimeEntityType.AddKey(
    new[] { id });
runtimeEntityType.SetPrimaryKey(key);

return runtimeEntityType;
}

public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
{
    var id = runtimeEntityType.FindProperty("Id");
    var completedAt = runtimeEntityType.FindProperty("CompletedAt");
    var errorMessage = runtimeEntityType.FindProperty("ErrorMessage");
    var itemsAutoResolved = runtimeEntityType.FindProperty("ItemsAutoResolved");
    var itemsCreated = runtimeEntityType.FindProperty("ItemsCreated");
    var itemsUpdated = runtimeEntityType.FindProperty("ItemsUpdated");
    var mappingsChecked = runtimeEntityType.FindProperty("MappingsChecked");
    var modelsFetched = runtimeEntityType.FindProperty("ModelsFetched");
    var providerType = runtimeEntityType.FindProperty("ProviderType");
    var startedAt = runtimeEntityType.FindProperty("StartedAt");
    var status = runtimeEntityType.FindProperty("Status");
    var triggeredBy = runtimeEntityType.FindProperty("TriggeredBy");
    var key = runtimeEntityType.FindKey(new[] { id });
    key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
    key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
    runtimeEntityType.SetOriginalValuesFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((ProviderMetadataSyncRun)(source.Entity));
            return ((ISnapshot)(new Snapshot<int, DateTime?, string, int, int, int, int, int, ProviderType, DateTime, string, string>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<DateTime?>(completedAt) == null ? null : ((ValueComparer<DateTime?>)(((IProperty)completedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime?>(completedAt))), (source.GetCurrentValue<string>(errorMessage) == null ? null : ((ValueComparer<string>)(((IProperty)errorMessage).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(errorMessage))), ((ValueComparer<int>)(((IProperty)itemsAutoResolved).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(itemsAutoResolved)), ((ValueComparer<int>)(((IProperty)itemsCreated).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(itemsCreated)), ((ValueComparer<int>)(((IProperty)itemsUpdated).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(itemsUpdated)), ((ValueComparer<int>)(((IProperty)mappingsChecked).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(mappingsChecked)), ((ValueComparer<int>)(((IProperty)modelsFetched).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(modelsFetched)), ((ValueComparer<ProviderType>)(((IProperty)providerType).GetValueComparer())).Snapshot(source.GetCurrentValue<ProviderType>(providerType)), ((ValueComparer<DateTime>)(((IProperty)startedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(startedAt)), (source.GetCurrentValue<string>(status) == null ? null : ((ValueComparer<string>)(((IProperty)status).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(status))), (source.GetCurrentValue<string>(triggeredBy) == null ? null : ((ValueComparer<string>)(((IProperty)triggeredBy).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(triggeredBy))))));
        });
    runtimeEntityType.SetStoreGeneratedValuesFactory(
        ISnapshot () => ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
    runtimeEntityType.SetTemporaryValuesFactory(
        ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int>(default(int)))));
    runtimeEntityType.SetShadowValuesFactory(
        ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
    runtimeEntityType.SetEmptyShadowValuesFactory(
        ISnapshot () => Snapshot.Empty);
    runtimeEntityType.SetRelationshipSnapshotFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((ProviderMetadataSyncRun)(source.Entity));
            return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
        });
    runtimeEntityType.SetCounts(new PropertyCounts(
        propertyCount: 12,
        navigationCount: 0,
        complexPropertyCount: 0,
        complexCollectionCount: 0,
        originalValueCount: 12,
        shadowCount: 0,
        relationshipCount: 1,
        storeGeneratedCount: 1));
    runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
    runtimeEntityType.AddAnnotation("Relational:Schema", null);
    runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
    runtimeEntityType.AddAnnotation("Relational:TableName", "ProviderMetadataSyncRuns");
    runtimeEntityType.AddAnnotation("Relational:ViewName", null);
    runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

    Customize(runtimeEntityType);
}

static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}
