// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using ConduitLLM.Configuration.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    public static class ProviderKeyCredentialUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(ProviderKeyCredential @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ApiKey>k__BackingField")]
        public static extern ref string ApiKey(ProviderKeyCredential @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BaseUrl>k__BackingField")]
        public static extern ref string BaseUrl(ProviderKeyCredential @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(ProviderKeyCredential @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsEnabled>k__BackingField")]
        public static extern ref bool IsEnabled(ProviderKeyCredential @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsPrimary>k__BackingField")]
        public static extern ref bool IsPrimary(ProviderKeyCredential @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<KeyName>k__BackingField")]
        public static extern ref string KeyName(ProviderKeyCredential @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderAccountGroup>k__BackingField")]
        public static extern ref short ProviderAccountGroup(ProviderKeyCredential @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProviderId>k__BackingField")]
        public static extern ref int ProviderId(ProviderKeyCredential @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SecretSettings>k__BackingField")]
        public static extern ref Dictionary<string, string> SecretSettings(ProviderKeyCredential @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref DateTime UpdatedAt(ProviderKeyCredential @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Provider>k__BackingField")]
        public static extern ref Provider Provider(ProviderKeyCredential @this);
    }
}
