// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using ConduitLLM.Configuration.Entities;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class RefundIdempotencyRecordEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "ConduitLLM.Configuration.Entities.RefundIdempotencyRecord",
                typeof(RefundIdempotencyRecord),
                baseEntityType,
                propertyCount: 7,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(RefundIdempotencyRecord).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RefundIdempotencyRecord).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.SetGetter(
                long (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.Id(instance),
                bool (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.Id(instance) == 0L);
            id.SetSetter(
                RefundIdempotencyRecord (RefundIdempotencyRecord instance, long value) =>
                {
                    RefundIdempotencyRecordUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                RefundIdempotencyRecord (RefundIdempotencyRecord instance, long value) =>
                {
                    RefundIdempotencyRecordUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                long (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<long>(0) : (entry.FlaggedAsTemporary(0) && RefundIdempotencyRecordUnsafeAccessors.Id(((RefundIdempotencyRecord)(entry.Entity))) == 0L ? entry.ReadTemporaryValue<long>(0) : RefundIdempotencyRecordUnsafeAccessors.Id(((RefundIdempotencyRecord)(entry.Entity))))),
                long (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.Id(((RefundIdempotencyRecord)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(id, 0),
                long (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<long>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<long>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTime),
                propertyInfo: typeof(RefundIdempotencyRecord).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RefundIdempotencyRecord).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            createdAt.SetGetter(
                DateTime (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.CreatedAt(instance),
                bool (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.CreatedAt(instance) == default(DateTime));
            createdAt.SetSetter(
                RefundIdempotencyRecord (RefundIdempotencyRecord instance, DateTime value) =>
                {
                    RefundIdempotencyRecordUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                RefundIdempotencyRecord (RefundIdempotencyRecord instance, DateTime value) =>
                {
                    RefundIdempotencyRecordUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                DateTime (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.CreatedAt(((RefundIdempotencyRecord)(entry.Entity))),
                DateTime (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.CreatedAt(((RefundIdempotencyRecord)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(createdAt, 1),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                keyComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v),
                providerValueComparer: new ValueComparer<DateTime>(
                    bool (DateTime v1, DateTime v2) => v1.Equals(v2),
                    int (DateTime v) => ((object)v).GetHashCode(),
                    DateTime (DateTime v) => v));
            createdAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var operationId = runtimeEntityType.AddProperty(
                "OperationId",
                typeof(string),
                propertyInfo: typeof(RefundIdempotencyRecord).GetProperty("OperationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RefundIdempotencyRecord).GetField("<OperationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            operationId.SetGetter(
                string (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.OperationId(instance),
                bool (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.OperationId(instance) == null);
            operationId.SetSetter(
                RefundIdempotencyRecord (RefundIdempotencyRecord instance, string value) =>
                {
                    RefundIdempotencyRecordUnsafeAccessors.OperationId(instance) = value;
                    return instance;
                });
            operationId.SetMaterializationSetter(
                RefundIdempotencyRecord (RefundIdempotencyRecord instance, string value) =>
                {
                    RefundIdempotencyRecordUnsafeAccessors.OperationId(instance) = value;
                    return instance;
                });
            operationId.SetAccessors(
                string (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.OperationId(((RefundIdempotencyRecord)(entry.Entity))),
                string (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.OperationId(((RefundIdempotencyRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(operationId, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(operationId));
            operationId.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            operationId.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(100)",
                    size: 100));
            operationId.TypeMapping = ((NpgsqlStringTypeMapping)operationId.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        operationId.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(operationId));
        operationId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var refundTransactionId = runtimeEntityType.AddProperty(
            "RefundTransactionId",
            typeof(long),
            propertyInfo: typeof(RefundIdempotencyRecord).GetProperty("RefundTransactionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(RefundIdempotencyRecord).GetField("<RefundTransactionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: 0L);
        refundTransactionId.SetGetter(
            long (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.RefundTransactionId(instance),
            bool (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.RefundTransactionId(instance) == 0L);
        refundTransactionId.SetSetter(
            RefundIdempotencyRecord (RefundIdempotencyRecord instance, long value) =>
            {
                RefundIdempotencyRecordUnsafeAccessors.RefundTransactionId(instance) = value;
                return instance;
            });
        refundTransactionId.SetMaterializationSetter(
            RefundIdempotencyRecord (RefundIdempotencyRecord instance, long value) =>
            {
                RefundIdempotencyRecordUnsafeAccessors.RefundTransactionId(instance) = value;
                return instance;
            });
        refundTransactionId.SetAccessors(
            long (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.RefundTransactionId(((RefundIdempotencyRecord)(entry.Entity))),
            long (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.RefundTransactionId(((RefundIdempotencyRecord)(entry.Entity))),
            long (IInternalEntry entry) => entry.ReadOriginalValue<long>(refundTransactionId, 3),
            long (IInternalEntry entry) => entry.GetCurrentValue<long>(refundTransactionId));
        refundTransactionId.SetPropertyIndexes(
            index: 3,
            originalValueIndex: 3,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        refundTransactionId.TypeMapping = LongTypeMapping.Default.Clone(
            comparer: new ValueComparer<long>(
                bool (long v1, long v2) => v1 == v2,
                int (long v) => ((object)v).GetHashCode(),
                long (long v) => v),
            keyComparer: new ValueComparer<long>(
                bool (long v1, long v2) => v1 == v2,
                int (long v) => ((object)v).GetHashCode(),
                long (long v) => v),
            providerValueComparer: new ValueComparer<long>(
                bool (long v1, long v2) => v1 == v2,
                int (long v) => ((object)v).GetHashCode(),
                long (long v) => v));
        refundTransactionId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var requestHash = runtimeEntityType.AddProperty(
            "RequestHash",
            typeof(string),
            propertyInfo: typeof(RefundIdempotencyRecord).GetProperty("RequestHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(RefundIdempotencyRecord).GetField("<RequestHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            maxLength: 64);
        requestHash.SetGetter(
            string (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.RequestHash(instance),
            bool (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.RequestHash(instance) == null);
        requestHash.SetSetter(
            RefundIdempotencyRecord (RefundIdempotencyRecord instance, string value) =>
            {
                RefundIdempotencyRecordUnsafeAccessors.RequestHash(instance) = value;
                return instance;
            });
        requestHash.SetMaterializationSetter(
            RefundIdempotencyRecord (RefundIdempotencyRecord instance, string value) =>
            {
                RefundIdempotencyRecordUnsafeAccessors.RequestHash(instance) = value;
                return instance;
            });
        requestHash.SetAccessors(
            string (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.RequestHash(((RefundIdempotencyRecord)(entry.Entity))),
            string (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.RequestHash(((RefundIdempotencyRecord)(entry.Entity))),
            string (IInternalEntry entry) => entry.ReadOriginalValue<string>(requestHash, 4),
            string (IInternalEntry entry) => entry.GetCurrentValue<string>(requestHash));
        requestHash.SetPropertyIndexes(
            index: 4,
            originalValueIndex: 4,
            shadowIndex: -1,
            relationshipIndex: -1,
            storeGenerationIndex: -1);
        requestHash.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
            comparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            keyComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            providerValueComparer: new ValueComparer<string>(
                bool (string v1, string v2) => v1 == v2,
                int (string v) => ((object)v).GetHashCode(),
                string (string v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "character varying(64)",
                size: 64));
        requestHash.TypeMapping = ((NpgsqlStringTypeMapping)requestHash.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
    requestHash.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var responseJson = runtimeEntityType.AddProperty(
        "ResponseJson",
        typeof(string),
        propertyInfo: typeof(RefundIdempotencyRecord).GetProperty("ResponseJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(RefundIdempotencyRecord).GetField("<ResponseJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
    responseJson.SetGetter(
        string (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.ResponseJson(instance),
        bool (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.ResponseJson(instance) == null);
    responseJson.SetSetter(
        RefundIdempotencyRecord (RefundIdempotencyRecord instance, string value) =>
        {
            RefundIdempotencyRecordUnsafeAccessors.ResponseJson(instance) = value;
            return instance;
        });
    responseJson.SetMaterializationSetter(
        RefundIdempotencyRecord (RefundIdempotencyRecord instance, string value) =>
        {
            RefundIdempotencyRecordUnsafeAccessors.ResponseJson(instance) = value;
            return instance;
        });
    responseJson.SetAccessors(
        string (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.ResponseJson(((RefundIdempotencyRecord)(entry.Entity))),
        string (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.ResponseJson(((RefundIdempotencyRecord)(entry.Entity))),
        string (IInternalEntry entry) => entry.ReadOriginalValue<string>(responseJson, 5),
        string (IInternalEntry entry) => entry.GetCurrentValue<string>(responseJson));
    responseJson.SetPropertyIndexes(
        index: 5,
        originalValueIndex: 5,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    responseJson.TypeMapping = StringTypeMapping.Default.Clone(
        comparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        keyComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        providerValueComparer: new ValueComparer<string>(
            bool (string v1, string v2) => v1 == v2,
            int (string v) => ((object)v).GetHashCode(),
            string (string v) => v),
        mappingInfo: new RelationalTypeMappingInfo(
            dbType: System.Data.DbType.String));
    responseJson.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var virtualKeyGroupId = runtimeEntityType.AddProperty(
        "VirtualKeyGroupId",
        typeof(int),
        propertyInfo: typeof(RefundIdempotencyRecord).GetProperty("VirtualKeyGroupId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(RefundIdempotencyRecord).GetField("<VirtualKeyGroupId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        sentinel: 0);
    virtualKeyGroupId.SetGetter(
        int (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.VirtualKeyGroupId(instance),
        bool (RefundIdempotencyRecord instance) => RefundIdempotencyRecordUnsafeAccessors.VirtualKeyGroupId(instance) == 0);
    virtualKeyGroupId.SetSetter(
        RefundIdempotencyRecord (RefundIdempotencyRecord instance, int value) =>
        {
            RefundIdempotencyRecordUnsafeAccessors.VirtualKeyGroupId(instance) = value;
            return instance;
        });
    virtualKeyGroupId.SetMaterializationSetter(
        RefundIdempotencyRecord (RefundIdempotencyRecord instance, int value) =>
        {
            RefundIdempotencyRecordUnsafeAccessors.VirtualKeyGroupId(instance) = value;
            return instance;
        });
    virtualKeyGroupId.SetAccessors(
        int (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.VirtualKeyGroupId(((RefundIdempotencyRecord)(entry.Entity))),
        int (IInternalEntry entry) => RefundIdempotencyRecordUnsafeAccessors.VirtualKeyGroupId(((RefundIdempotencyRecord)(entry.Entity))),
        int (IInternalEntry entry) => entry.ReadOriginalValue<int>(virtualKeyGroupId, 6),
        int (IInternalEntry entry) => entry.GetCurrentValue<int>(virtualKeyGroupId));
    virtualKeyGroupId.SetPropertyIndexes(
        index: 6,
        originalValueIndex: 6,
        shadowIndex: -1,
        relationshipIndex: -1,
        storeGenerationIndex: -1);
    virtualKeyGroupId.TypeMapping = IntTypeMapping.Default.Clone(
        comparer: new ValueComparer<int>(
            bool (int v1, int v2) => v1 == v2,
            int (int v) => v,
            int (int v) => v),
        keyComparer: new ValueComparer<int>(
            bool (int v1, int v2) => v1 == v2,
            int (int v) => v,
            int (int v) => v),
        providerValueComparer: new ValueComparer<int>(
            bool (int v1, int v2) => v1 == v2,
            int (int v) => v,
            int (int v) => v),
        mappingInfo: new RelationalTypeMappingInfo(
            storeTypeName: "integer"));
    virtualKeyGroupId.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(virtualKeyGroupId));
    virtualKeyGroupId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var key = runtimeEntityType.AddKey(
        new[] { id });
    runtimeEntityType.SetPrimaryKey(key);

    var index = runtimeEntityType.AddIndex(
        new[] { virtualKeyGroupId, operationId },
        unique: true);

    return runtimeEntityType;
}

public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
{
    var id = runtimeEntityType.FindProperty("Id");
    var createdAt = runtimeEntityType.FindProperty("CreatedAt");
    var operationId = runtimeEntityType.FindProperty("OperationId");
    var refundTransactionId = runtimeEntityType.FindProperty("RefundTransactionId");
    var requestHash = runtimeEntityType.FindProperty("RequestHash");
    var responseJson = runtimeEntityType.FindProperty("ResponseJson");
    var virtualKeyGroupId = runtimeEntityType.FindProperty("VirtualKeyGroupId");
    var key = runtimeEntityType.FindKey(new[] { id });
    key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<long>(key));
    key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<long>(key));
    runtimeEntityType.SetOriginalValuesFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((RefundIdempotencyRecord)(source.Entity));
            return ((ISnapshot)(new Snapshot<long, DateTime, string, long, string, string, int>(((ValueComparer<long>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(id)), ((ValueComparer<DateTime>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(createdAt)), (source.GetCurrentValue<string>(operationId) == null ? null : ((ValueComparer<string>)(((IProperty)operationId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(operationId))), ((ValueComparer<long>)(((IProperty)refundTransactionId).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(refundTransactionId)), (source.GetCurrentValue<string>(requestHash) == null ? null : ((ValueComparer<string>)(((IProperty)requestHash).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(requestHash))), (source.GetCurrentValue<string>(responseJson) == null ? null : ((ValueComparer<string>)(((IProperty)responseJson).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(responseJson))), ((ValueComparer<int>)(((IProperty)virtualKeyGroupId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(virtualKeyGroupId)))));
        });
    runtimeEntityType.SetStoreGeneratedValuesFactory(
        ISnapshot () => ((ISnapshot)(new Snapshot<long>(((ValueComparer<long>)(((IProperty)id).GetValueComparer())).Snapshot(default(long))))));
    runtimeEntityType.SetTemporaryValuesFactory(
        ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<long>(default(long)))));
    runtimeEntityType.SetShadowValuesFactory(
        ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
    runtimeEntityType.SetEmptyShadowValuesFactory(
        ISnapshot () => Snapshot.Empty);
    runtimeEntityType.SetRelationshipSnapshotFactory(
        ISnapshot (IInternalEntry source) =>
        {
            var structuralType = ((RefundIdempotencyRecord)(source.Entity));
            return ((ISnapshot)(new Snapshot<long>(((ValueComparer<long>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<long>(id)))));
        });
    runtimeEntityType.SetCounts(new PropertyCounts(
        propertyCount: 7,
        navigationCount: 0,
        complexPropertyCount: 0,
        complexCollectionCount: 0,
        originalValueCount: 7,
        shadowCount: 0,
        relationshipCount: 1,
        storeGeneratedCount: 1));
    runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
    runtimeEntityType.AddAnnotation("Relational:Schema", null);
    runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
    runtimeEntityType.AddAnnotation("Relational:TableName", "RefundIdempotencyRecords");
    runtimeEntityType.AddAnnotation("Relational:ViewName", null);
    runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

    Customize(runtimeEntityType);
}

static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}
