// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using ConduitLLM.Configuration.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ConduitLLM.Configuration.Data.CompiledModels
{
    public static class WebhookReplayAuditUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OperationId>k__BackingField")]
        public static extern ref Guid OperationId(WebhookReplayAudit @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Actor>k__BackingField")]
        public static extern ref string Actor(WebhookReplayAudit @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Cycle>k__BackingField")]
        public static extern ref int Cycle(WebhookReplayAudit @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DeadLetterId>k__BackingField")]
        public static extern ref Guid? DeadLetterId(WebhookReplayAudit @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DeliveryId>k__BackingField")]
        public static extern ref string DeliveryId(WebhookReplayAudit @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PreviousAttempts>k__BackingField")]
        public static extern ref int PreviousAttempts(WebhookReplayAudit @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RequestedAt>k__BackingField")]
        public static extern ref DateTime RequestedAt(WebhookReplayAudit @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RetainUntil>k__BackingField")]
        public static extern ref DateTime RetainUntil(WebhookReplayAudit @this);
    }
}
